.github/labeler.yml, .github/workflows/labeler.yml
As per:
https://github.com/actions/labeler
=> feat: set up automatic labelling of pull requests

.github/dependabot.yml, .github/labeler.yml, .github/workflows/ci.yml, .github/workflows/labeler.yml, package.json, projects/npm-tools/.travis.yml
Seeing as [Prettier has supported YAML for a long time now](https://prettier.io/blog/2018/07/29/1.14.0.html), we may as well use it.
=> feat: format YAML files with Prettier

CONTRIBUTING/importing-a-project.md, CONTRIBUTING/migrating-an-npm-package-to-the-liferay-named-scope.md
Seeing as we have added some new config files lately, let's add a reminder here about keeping them up-to-date.
=> docs: make additional notes about how to keep repo "meta" stuff up-to-date

projects/npm-tools/packages/changelog-generator/src/index.js
Previously, the changelog-generator would work with single-project repos:
CHANGELOG.md
package.json
...
or monorepos with this fixed structure:
package.json
packages/
a/
package.json
...
b/
package.json
...
...
When working with monorepos, there would typically be a single `.yarnrc` at the top and a shared changelog:
.yarnrc
CHANGELOG.md
package.json
packages/
a/
package.json
...
b/
package.json
...
...
or per-package changelogs with per-package `.yarnrc` files:
package.json
packages/
a/
.yarnrc
CHANGELOG.md
package.json
...
b/
.yarnrc
CHANGELOG.md
package.json
...
...
We also supported working in repos without `.yarnrc` files, but that isn't the common case for us, especially in repos that use the `js-publish` package to do their releases.
With the new monorepo, we have a more …
=> feat: teach the changelog-generator to work with new monorepo structure

projects/eslint-config/CONTRIBUTING.md
Just some tweaks I wanted to get in before cutting a release.
=> docs(eslint-config): tweak CONTRIBUTING.md

projects/npm-tools/packages/npm-scripts/package.json
[Release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/eslint-config%2Fv21.2.0)
=> chore(npm-scripts): update eslint-config dependency to v21.2.0

projects/eslint-config/package.json, yarn.lock
Seeing as I have to cut a release today, may as well update this, seeing as we were just notified about it in [#111](https://github.com/liferay/liferay-frontend-projects/pull/111).
=> chore(eslint-config): update eslint-plugin-react to v7.21.3

.github/ISSUE_TEMPLATE/js-toolkit.md
Nothing much to see here. This is very like [the eslint-config template](https://github.com/liferay/liferay-frontend-projects/blob/master/.github/ISSUE_TEMPLATE/eslint-config.md).
=> chore: configure issue template for js-toolkit

CONTRIBUTING/importing-a-project.md
Given that the js-toolkit import was quite complicated (two branches, 35 packages), I figure it warrants noting more detail in this document about how to update that kind of thing.
=> docs(monorepo): add a bunch more detail on how to import a project

projects/npm-tools/packages/npm-scripts/package.json
Release notes:
- https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-bundler-preset-liferay-dev%2Fv4.6.5
Just a routine dep update.
=> chore(npm-scripts): update preset dependency to v4.6.5

projects/npm-tools/packages/npm-scripts/src/scripts/storybook.js, projects/npm-tools/packages/npm-scripts/src/storybook/README.md, projects/npm-tools/packages/npm-scripts/src/storybook/config.js, projects/npm-tools/packages/npm-scripts/src/storybook/middleware.js
Just some small fixes:
- update storybook's node path
- rename `index.es.js` to `index.js`
- update using `http-proxy-middleware` https://stackoverflow.com/questions/58431098/create-react-app-http-proxy-middleware-not-working
@thektan
=> feat(npm-scripts): fix storybook

projects/npm-tools/CONTRIBUTING.md
As asked for [here](https://github.com/liferay/liferay-frontend-projects/pull/234#issuecomment-726936853).
=> docs(npm-scripts): add instructions on how to integrate releases

projects/npm-tools/packages/npm-scripts/src/scripts/webpack.js, projects/npm-tools/packages/npm-scripts/test/scripts/webpack.js
This fixes issue #243 
I have tested it in my local portal repo.
=> fix(npm-scripts): webpack watch feature

maintenance/projects/js-toolkit/lerna.json
Same thing as [fixed here](https://github.com/liferay/liferay-frontend-projects/pull/278).
I've made [an issue for applying permanent fix](https://github.com/liferay/liferay-frontend-projects/issues/293).
=> style(js-toolkit): fix formatting

projects/npm-tools/packages/npm-scripts/package.json
As per https://github.com/liferay/liferay-frontend-projects/pull/307#pullrequestreview-557358660
=> chore(npm-scripts): add missing dependency

package.json, projects/js-toolkit/packages/js-toolkit-core/package.json, projects/js-toolkit/packages/npm-bundler/package.json, projects/js-toolkit/tsconfig.json, projects/npm-tools/packages/npm-scripts/package.json, projects/npm-tools/packages/npm-scripts/src/utils/createFederationConfig.js, yarn.lock
See commits for more info.
This is the final step needed for [LPS-24287](https://issues.liferay.com/browse/LPS-124287)
I will merge this and release a new version so that I can make a server side PR to be tested in CI.
The server counterpart of this PR is in a private [branch](https://github.com/izaera/liferay-portal/tree/LPS-124287-followup) until this gets merged and released.
=> feat: upgrade webpack and add more portal projects to federated build

projects/eslint-config/utils/local.js
While following up on [#429](https://github.com/liferay/liferay-frontend-projects/pull/429) I went to update alloy-editor's lint set-up (which is very old) and noticed that ESLint has been doing some refactoring that means that newer versions don't work properly with our monkey-patching technique, and need to be updated again.
Now, the monkey patching has _always_ sucked, and we know how to restructure our code so that we won't need any more, but it will require quite a bit of work (see [#9](https://github.com/liferay/liferay-frontend-projects/issues/9)); in short, it means creating a plugin package and using that instead of the existing config package, because configs cannot contain plugins but plugins can contain configs.
Anyway, I don't want to do that now because it is probably a full …
=> fix(eslint-config): update monkey patching to work with newer ESLint

projects/npm-tools/packages/npm-scripts/package.json
Brings with it a bunch of shiny new rules and enhancements as described in [the release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/eslint-config%2Fv22.0.0):
-   feat(eslint-config)!: teach class-names rules about "customClassName" attributes
-   feat(eslint-config)!: disallow unnecessary string interpolation in JSX
-   feat(eslint-config)!: activate no-eval rule
-   feat(eslint-config)!: teach sort-imports, group-imports to separate type-only inputs
-   feat(eslint-config)!: teach import-extensions rule about .ts, .tsx
-   feat(eslint-config): teach no-duplicate-imports rule about type imports
-   feat(eslint-config)!: turn off no-for-of-loops rule by default
-   fix(eslint-config): update monkey patching to work with newer ESLint
-   test(eslint-config): …
=> chore(npm-scripts)!: update bundled @liferay/eslint-config to v22.0.0

projects/npm-tools/packages/changelog-generator/src/index.js
Motivated by [today's Slack thread](https://liferay.slack.com/archives/C3JBR21HA/p1616068068087200), this should help us follow SemVer a little more consistently, even if you don't know that we follow SemVer in our projects.
This doesn't handle every single case in which a version bump should be major, but it does handle the common case of running in `--interactive` mode and then letting the user choose from the list. Basically, if any of the changes are breaking, it will print a warning that says:
Breaking changes detected; "major" or "premajor" version recommended.
We don't force it, but we strongly hint that the user should do it.
What cases doesn't this handle? Well, if you're not running in `--interactive` mode, or you explicitly supply a spelled-out version number, we don't check …
=> feat(changelog-generator): suggest when version bump should be major

maintenance/projects/js-toolkit/CONTRIBUTING.md
There are more ways to test this, but this one is the safest I've found and especially it works with
`ant all` too, which is not an easy thing because it tends to destroy any links or manual copies
you may have in your `node_modules` folder.
=> docs(js-toolkit): add documentation on how to test JS Toolkit locally in liferay-portal

maintenance/projects/js-toolkit/packages/liferay-npm-bundler-loader-css-loader/src/index.js
This is needed for [LPS-129367](https://issues.liferay.com/browse/LPS-129367), otherwise the portal does not build.
I will need to release a new version of the toolkit and npm-scripts after this is merged.
=> fix(js-toolkit): don't fail in css-loader for scoped dependencies

projects/npm-tools/packages/npm-scripts/package.json
[Release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/eslint-config%2Fv24.0.0) below. Note this a (light) breaking change because it requires some small tweaks in liferay-portal in order to be complete (see https://github.com/liferay/liferay-frontend-projects/pull/471).
---
[Full changelog](https://github.com/liferay/liferay-frontend-projects/compare/eslint-config/v23.0.0...eslint-config/v24.0.0)
-   feat(eslint-config)!: adapt no-use-before-define set-up for TypeScript ([\#471](https://github.com/liferay/liferay-frontend-projects/pull/471))
-   feat(eslint-config)!: adapt no-use-before-define set-up for TypeScript ([\#471](https://github.com/liferay/liferay-frontend-projects/pull/471))
-   chore: update lint-related dependencies …
=> chore(npm-scripts)!: bump eslint-config to v24.0.0

maintenance/projects/js-toolkit/CONTRIBUTING.md, maintenance/projects/js-toolkit/resources/devtools/link-js-toolkit/setup-yarn-workspace.js
This is so that contributors now how to test local modifications to the Toolkit
=> chore: document and enhance link-js-toolkit tool

guidelines/general/typescript.md, projects/npm-tools/packages/npm-scripts/src/typescript/README.md
With recent changes in our TS build and adoption in DXP, it's time to update this document. Closing the related issue because even an initial list like this is not a bad starting point. We can always invest more in building up the list over time, but I don't really feel like scouring the internet for learning materials right now; I think we should just get to work and observe what kind of questions/needs get surfaced.
Note I'm also including a back-link to the updated page from our "build" docs.
Closes: https://github.com/liferay/liferay-frontend-projects/issues/481
=> docs(guidelines): document some additional TS resources

CONTRIBUTING/importing-a-project.md
As this may be non-obvious, want to document what I did to update my "merge Senna history" PR that had been sitting abandoned for three months.
Seeing as we now have quite a few examples, and they are wordy, added some headings to make it easier to know where you are in the doc.
=> docs(monorepo): provide example of how to "rebase" (redo) subtree merge

maintenance/projects/senna/README.md
This was an item [on the TODO list here](https://github.com/liferay/liferay-frontend-projects/pull/379#issuecomment-823460375).
=> docs(senna): remove broken badges from README

projects/npm-tools/packages/npm-scripts/package.json
[Release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/eslint-config%2Fv24.0.1).
Basically contains [exactly one fix](https://github.com/liferay/liferay-frontend-projects/pull/517), for [this issue](https://github.com/liferay/liferay-frontend-projects/issues/515).
=> chore(npm-scripts): update eslint-config to v24.0.1

projects/npm-tools/packages/npm-scripts/package.json
Update to latest liferay-theme-tasks versions to avoid yarn duplication in the repo
=> feat(npm-scripts): update liferay-theme-tasks version

support/github-to-jira-synchronization/clay.md, support/github-to-jira-synchronization/liferay-frontend-projects.md
Just updated the user mappings (GH-Jira) in frontend-projects and Clay Jira-Exalate sync scripts.
=> docs(gh-jira-sync): update exalate user mapping adding headless squad

maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/index.ts, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/__tests__/dependencies.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/dependencies.js, maintenance/projects/js-toolkit/scripts/watch.js
This is chunk 1 of https://github.com/liferay/liferay-frontend-projects/pull/562
Fixes #566
=> feat(js-toolkit): automatically exclude transitive dependencies from autopresets (target platforms)

projects/eslint-config/plugins/portal/docs/rules/no-react-dom-create-portal.md, projects/eslint-config/plugins/portal/tests/lib/rules/no-react-dom-create-portal.js, projects/eslint-config/portal.js
I forgot to enable the rule by default
=> fix(eslint-config): forgot to apply rule by default and include docs for the rule

projects/npm-tools/packages/npm-scripts/CHANGELOG.md
rough day here with my publishes. Hopefully they should be good now after this
=> chore(npm-scripts): fix CHANGELOG

guidelines/dxp/extracting_js_from_jsps.md
Fixes #344 
Let me know if I missed something or misrepresented some information!
=> docs(guidelines): Add docs on extracting JS from JSPs

projects/js-themes-toolkit/packages/bs3-bs4-compat/.yarnrc, projects/js-themes-toolkit/packages/bs3-bs4-compat/README.md, projects/js-themes-toolkit/packages/bs3-bs4-compat/package.json, projects/js-themes-toolkit/packages/liferay-theme-tasks/theme/tasks/upgrade.js
Make sure naming is consistent
=> chore(bs3-bs4-compat): make sure naming is consistent

projects/js-toolkit/packages/liferay-cli/package.json, projects/js-toolkit/packages/liferay-cli/src/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/index.ts, yarn.lock
=> feat(liferay-cli): check for updates

projects/npm-tools/packages/npm-scripts/package.json
This updates to the latest version of eslint-config
=> feat(npm-scripts): update eslint-config version

projects/npm-tools/packages/npm-scripts/package.json
=> feat(npm-scripts): update eslint-config version to 27.0.1

projects/js-themes-toolkit/packages/bs3-bs4-compat/scss/_mixins.scss, projects/js-themes-toolkit/packages/bs3-bs4-compat/scss/_variables.scss, projects/js-themes-toolkit/packages/bs3-bs4-compat/scss/components/_form_validation.scss
fixes #653
Fixes broken colors when building with the compat layer
=> fix(bs3-bs4-compat): fix broken color variables

projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/index.js
Fix of https://github.com/liferay/liferay-frontend-projects/commit/1e3409fb9841d0940253b49d201a5d1769c713eb#diff-d3e4cdb5bef9c555bf156bcc0dbd078335680bee264d420a6393d3e6e935ff6d
Manual test: https://codepen.io/eduardoallegrini/pen/KKqGKyr?editors=0011
=> fix(js-theme-toolkit): Fix RTL conversion for translate properties

projects/npm-tools/packages/npm-scripts/package.json
=> fix(npm-scripts): update liferay-theme-tasks to latest version

projects/eslint-plugin/rules/portal/lib/rules/no-global-fetch.js, projects/eslint-plugin/rules/portal/tests/lib/rules/no-global-fetch.js
Fixes https://github.com/liferay/liferay-frontend-projects/issues/624
Lemme know if I did it properly, I couldn't come up with a different solution.
/cc @jbalsas
=> chore(eslint-plugin): lint to accept "fetch", not "fetch.es"

projects/npm-tools/packages/npm-scripts/src/config/prettier.json
Error in dxp without this sorted properly.
=> fix(npm-scripts): sort prettier config

projects/eslint-plugin/configs/general.js, projects/eslint-plugin/rules/general/docs/rules/no-conditional-object-keys.md, projects/eslint-plugin/rules/general/index.js, projects/eslint-plugin/rules/general/lib/rules/no-conditional-object-keys.js, projects/eslint-plugin/rules/general/tests/lib/rules/no-conditional-object-keys.js
follow up from https://github.com/liferay/liferay-frontend-projects/pull/692
=> fix(eslint-plugin): update no-conditional-object-keys rule

projects/npm-tools/packages/npm-scripts/package.json
=> feat(npm-scripts): bump eslint-plugin version

projects/js-toolkit/packages/liferay-cli/src/new/facet-angular/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/facet-plain-js/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/facet-react/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/facet-shared-bundle/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/facet-shared-bundle/templates/.babelrc.ejs, projects/js-toolkit/packages/liferay-cli/src/new/facet-shared-bundle/templates/src/index.js.ejs, projects/js-toolkit/packages/liferay-cli/src/new/facet-vuejs/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/target-liferay/index.ts, projects/js-toolkit/qa/.gitignore, projects/js-toolkit/scripts/qa/index.js
Implementation of https://issues.liferay.com/browse/IFI-2718
This adds a new type of project to the generator so that we don't leave any gap in the previous implementation based on a Yeoman generator.
=> feat: migrate shared bundle generation to @liferay/cli 

projects/js-themes-toolkit/packages/generator-liferay-theme/package.json, projects/npm-tools/packages/npm-scripts/package.json
updates packages dependent on theme-tasks
=> feat(npm-scripts): update liferay-theme-tasks dependency version

projects/eslint-plugin/rules/general/lib/rules/no-get-data-attribute.js, projects/eslint-plugin/rules/general/tests/lib/rules/no-get-data-attribute.js
=> fix(eslint-plugin): dataset uses camelCased keys instead of kebab-case.

.github/workflows/format.yml, .github/workflows/guidelines.yml, .github/workflows/js-toolkit-v2.yml, .github/workflows/lint.yml, .github/workflows/lockfile.yml, .github/workflows/projects.yml, projects/js-themes-toolkit/packages/bs3-bs4-compat/package.json, projects/js-themes-toolkit/packages/generator-liferay-theme/package.json, projects/js-themes-toolkit/packages/liferay-theme-tasks/package.json
Updating our engines specification to match node lts
=> chore: update engines field to match our node lts

projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/devDependencies.js
Updating this for new release of theme generators
=> feat(theme-tasks): update liferay-font-awesome version reference

package.json, projects/js-themes-toolkit/qa/package.json, projects/js-themes-toolkit/scripts/qa.js, third-party/projects/alloy-font-awesome/package.json, yarn.lock
Had to make some adjustments to the workspace so that the qa script passed successfully
=> fix(js-themes-toolkit): update for qa script

maintenance/projects/js-toolkit/packages/generator-liferay-js/src/adapt/index.js, maintenance/projects/js-toolkit/packages/generator-liferay-js/src/app/index.js, maintenance/projects/js-toolkit/packages/generator-liferay-js/src/utils/index.js
Just show a message to users as per point 9 of #740
=> feat(generator-liferay-js): encourage users to use @liferay/cli

.github/workflows/update-dependencies.yml
This workflow runs daily and creates a new issue for us in the case that a new liferay-portal version has been released
=> chore: add workflow for checking for new Liferay releases

projects/eslint-plugin/rules/aui/lib/rules/no-all.js, projects/eslint-plugin/rules/aui/lib/rules/no-array.js, projects/eslint-plugin/rules/aui/lib/rules/no-each.js, projects/eslint-plugin/rules/aui/lib/rules/no-node.js, projects/eslint-plugin/rules/aui/lib/rules/no-one.js, projects/eslint-plugin/rules/aui/lib/utils/checkAUIScope.js, projects/eslint-plugin/rules/aui/tests/lib/rules/no-node.js
fixes https://github.com/liferay/liferay-frontend-projects/issues/780
Thought here is to scope down our rule here so that we aren't requiring fixes in existing aui modules
=> fix(eslint-plugin): update aui rules to only error if used outside of an aui module

maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/empty-with-portlet/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/index.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/jar.ts, projects/js-toolkit/docs/reference/dot-npmbundlerrc.md
See https://issues.liferay.com/browse/IFI-2927
I'm going to merge this as soon as it becomes green to be able to release a new version.
=> fix: don't break deployment for shared bundle projects

maintenance/projects/js-toolkit/packages/generator-liferay-js/src/adapt/index.js, maintenance/projects/js-toolkit/packages/generator-liferay-js/src/app/index.js, maintenance/projects/js-toolkit/packages/generator-liferay-js/src/utils/index.js
See https://liferay.slack.com/archives/C3JBR21HA/p1640156432021500 for internal reference about the discussion.
=> feat(generator-liferay-js): remove @liferay/cli spam

projects/js-themes-toolkit/packages/liferay-theme-tasks/theme/tasks/upgrade.js
See https://issues.liferay.com/browse/LPP-43860
=> fix(js-themes-toolkit): mark completion of upgrade:css

projects/npm-tools/packages/npm-scripts/src/config/npmscripts.config.js
Fixes #822 
Thanks @bryceosterhaus for the catch!
=> feat(npm-scripts): Add "extra" to the list of folders to check with yarn format

projects/js-toolkit/packages/liferay-cli/src/new/target-remote-app/index.ts
I'll ninjamerge :ninja: this as it is a small fix
=> fix(liferay-cli): remove leftover from copypasta 🍝

projects/amd-loader/CHANGELOG.md, projects/amd-loader/package.json, support/packages/local-npm/lib/index.js
=> fix(local-npm): prevent local-npm from screwing NodePlugin

projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdExportsBridges.js, projects/npm-tools/packages/npm-scripts/src/utils/getMergedConfig.js, projects/npm-tools/packages/npm-scripts/src/utils/runWebpack.js, projects/npm-tools/packages/npm-scripts/src/utils/runWebpackAsBundler.js
See commits for a full explanation on what this PR does.
This is to be tested against https://github.com/liferay-frontend/liferay-portal/pull/1955 as per https://github.com/liferay-frontend/liferay-portal/pull/1955#issuecomment-1057983985.
=> feat(npm-scripts): support bridged exports

projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdExportsBridges.js, projects/npm-tools/packages/npm-scripts/src/utils/runWebpackAsBundler.js
I'll merge if it's green to continue running CI for https://github.com/liferay-frontend/liferay-portal/pull/1955#issuecomment-1061087242
=> fix(npm-scripts): fix ESM to AMD bridges

projects/js-themes-toolkit/packages/bs3-bs4-compat/README.md
We no longer provide a main file in this package
=> chore(bs3-bs4-compat): remove reference to main file

guidelines/dxp/liferay_global_event_bus.md
fixes https://github.com/liferay/liferay-frontend-projects/issues/888
=> chore(guidelines): add full example for event bus

.github/workflows/triage.yml
=> chore(workflows): add assignee to message in issue

projects/js-toolkit/packages/liferay-cli/bin/liferay.js, projects/js-toolkit/packages/portal-base/src/index.ts, projects/js-toolkit/scripts/watch.js
See https://github.com/liferay/liferay-frontend-projects/issues/850#issuecomment-1036210123
=> feat(js-toolkit): add --only option to @liferay/cli

projects/js-toolkit/packages/dev-server/src/server.ts
Hey @ktor, sorry for the delay in getting to your [initial PR](https://github.com/liferay/liferay-frontend-projects/pull/831). We actually added something similar to our prettier script. Can you test out my changes here and see if it works for you? I think this a more accurate way to locate the workspace root
=> feat(dev-server): add support for workspaces

third-party/projects/alloy-font-awesome/css/font-awesome.css, third-party/projects/alloy-font-awesome/less/icons-alloy.less, third-party/projects/alloy-font-awesome/scss/_icons-alloy.scss, third-party/projects/alloy-font-awesome/src/assets/font-awesome/less/icons-alloy.less, third-party/projects/alloy-font-awesome/src/assets/font-awesome/scss/_icons-alloy.scss
Similar to what we did on https://github.com/liferay/clay/issues/4683 see https://github.com/liferay/clay/pull/4927
=> fix(liferay-font-awesome): Updates content property values to conform to what is allowed by OAW Tracker

projects/npm-tools/packages/npm-scripts/src/jest/mocks/Liferay.js
This PR aims to move pretty much all of the local Jest mocks (found inside whichever file is declared as the host of Jest configs) into a global place inside of npm-scripts.
I forget how exactly we do versions for npm-scripts (or any project here), but we can bump the version of this and then update `package.json` to the new version inside the counterpart PR in `liferay-portal`. 
This PR doesn't do anything, and it will probably cause issues, if it makes it into `liferay-portal` without its counterpart.
=> feat(npm-scripts): add more default values for our mocks in DXP

projects/npm-tools/packages/npm-scripts/src/jest/mocks/Liferay.js
Counterpart of https://github.com/liferay-frontend/liferay-portal/pull/2411
=> feat(npm-scripts): Add more commonly used jest mocks to our exported mocks

projects/js-themes-toolkit/packages/liferay-theme-tasks/theme/tasks/build/sass.js, projects/npm-tools/packages/npm-scripts/src/sass/build.js
fixes https://github.com/liferay/liferay-frontend-projects/issues/965
=> feat(npm-scripts): add minification when NODE_ENV is production

projects/npm-tools/packages/npm-scripts/src/jest/mocks/Liferay.js
@bryceosterhaus More additions to fix failing tests in the [liferay-portal's side of this task](https://github.com/liferay-frontend/liferay-portal/pull/2411#issuecomment-1173541533)
=> feat(npm-scripts): Improve existing Jest mocks

third-party/projects/alloy-ui/src/aui-scheduler/assets/aui-scheduler-base-core.css, third-party/projects/alloy-ui/src/aui-scheduler/js/aui-scheduler-base-event.js
https://issues.liferay.com/browse/AUI-3212
This fix is to resolve the accessibility issue here: https://github.com/liferay/liferay-frontend-projects/issues/978
Let me know if there are any questions or comments about this.
Thank you!
=> fix(alloy-ui): AUI-3212 Created new Event to display ResourceName

projects/js-toolkit/packages/js-toolkit-core/src/project/liferayCli/Build.ts, projects/js-toolkit/packages/portal-base/package.json, projects/js-toolkit/packages/portal-base/src/build/bundler2.ts, projects/js-toolkit/packages/portal-base/src/util/getWebpackConfiguration.ts, projects/js-toolkit/packages/portal-base/src/util/runSass.ts, support/packages/local-npm/lib/index.js, yarn.lock
=> feat(js-toolkit): minify output (code and CSS) in @liferay/cli projects

third-party/projects/alloy-ui/src/aui-datepicker/js/aui-datepicker-delegate.js, third-party/projects/alloy-ui/src/aui-datepicker/js/aui-datepicker-popover.js, third-party/projects/alloy-ui/src/aui-datepicker/js/aui-datepicker.js
Caused by pull https://github.com/liferay/liferay-frontend-projects/pull/975
This is a temporary solution to fix the regression https://issues.liferay.com/browse/LPS-160083. We should develop a more elaborated one for the original case.
@bryceosterhaus When you can, please review and release a new version. Thanks!
=> revert(alloy-ui): LPS-160083 calendar event date picker

third-party/projects/alloy-ui/src/aui-datatable/assets/aui-datatable-base-cell-editor-core.css
[LPS-121218](https://issues.liferay.com/browse/LPS-121218)
https://user-images.githubusercontent.com/64814287/183974369-7ff358e1-0a04-460d-8184-9977956aced1.mp4
=> fix(alloy-ui): LPS-121218 Add .color-cell-editor-hidden in css file

projects/js-toolkit/packages/js-toolkit-core/src/project/liferayCli/Deploy.ts
=> fix(js-toolkit-core): fix "No such file or directory .liferay.json" error

.github/workflows/projects.yml, projects/js-toolkit/packages/portal-adapt-base/src/loader/addCSSPortletHeader.ts, target-platforms/packages/portal-adapt-create-react-app/config.json
=> fix: hard-coded css/main.css file in create-react-app adaptations

projects/js-toolkit/packages/portal-base/src/util/runConfigureWizard.ts
forgot this commit in https://github.com/liferay/liferay-frontend-projects/pull/1004 :-(
=> style(portal-base): remove deep import

maintenance/projects/js-toolkit/packages/liferay-npm-bundler-plugin-tweak-sourcemaps/README.md, maintenance/projects/js-toolkit/packages/liferay-npm-bundler-plugin-tweak-sourcemaps/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-bundler-plugin-tweak-sourcemaps/src/index.ts, maintenance/projects/js-toolkit/packages/liferay-npm-bundler-plugin-tweak-sourcemaps/tsconfig.json, maintenance/projects/js-toolkit/packages/liferay-npm-bundler-preset-standard/config.json, maintenance/projects/js-toolkit/packages/liferay-npm-bundler-preset-standard/package.json
=> fix: MVC portlet source maps point to a wrong place

projects/js-toolkit/packages/js-toolkit-core/src/project/liferayCli/persist.ts
=> fix(js-toolkit-core): deployment wizard fails to persist Liferay's path

third-party/projects/alloy-ui/src/aui-parse-content/js/aui-parse-content.js
Fixes error #2 of https://github.com/liferay-frontend/liferay-portal/pull/2749#issuecomment-1261813605
=> fix(alloy-ui): fix aui-parse-content

projects/npm-tools/packages/npm-scripts/src/utils/runWebpackAsBundler.js
This fixes https://github.com/liferay/liferay-frontend-projects/pull/1038#issuecomment-1297082745 :roll_eyes:
=> fix: import TerserPlugin correctly

projects/npm-tools/packages/npm-scripts/src/index.js, projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/src/scripts/cache.js, projects/npm-tools/packages/npm-scripts/src/scripts/types.js, projects/npm-tools/packages/npm-scripts/src/utils/buildArtifacts.js
Handful of additions here. Take a look at commit history for specifics
=> feat(npm-scripts): fix which files are added to cache and add new commands to interact with cache

third-party/projects/alloy-ui/src/aui-autosize/js/aui-autosize-iframe.js
Hello Team,
This PR is to solve an issue related to aui-autosize-iframe, please help to review this PR.
Issue: https://issues.liferay.com/browse/LPS-163952 The details page is loaded but you only see the bottom part.
PTR: https://issues.liferay.com/browse/PTR-3350
Thank you very much,
Chi
=> fix: Handle scroll to into view after change height in aui-autosize-iframe.js

projects/npm-tools/packages/npm-scripts/src/utils/runWebpackAsBundler.js
Fix for https://issues.liferay.com/browse/LPS-168469
=> fix: generate source maps correctly

projects/npm-tools/packages/npm-scripts/src/config/npmscripts.config.js, projects/npm-tools/packages/npm-scripts/src/typescript/runTSC.js
Not sure how I didn't catch this TS issue before, but shoudl be fixed now
=> fix(npm-scripts): remove type file instead of source file, which didn't even exist in the first place

third-party/projects/alloy-ui/src/aui-image-viewer/js/aui-image-viewer-base.js, third-party/projects/alloy-ui/src/aui-image-viewer/js/aui-image-viewer.js
Hi guys,
Can you review this pull request, please?
There are 3 issues to fix:
1. Images without text alternative: This is addressed by passing image description in links object and then adding it to img element.
2. Empty headers: This is addressed by replacing wrong h4 and h5 elements by span with h4 and h5 css class.
3. Links with empty text: This is addressed by adding some text specific for screen readers.
Thanks.
Regards.
=> fix(alloy-ui): AUI-3217 Fix accessibility issues in Image Viewer Component

projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/devDependencies.js
Ran `yarn themeDeps:update` inside `/projects/js-themes-toolkit`.
=> feat: update theme deps to latest version numbers

projects/npm-tools/packages/npm-scripts/src/utils/getExternalExportsWebpackConfigs.js, projects/npm-tools/packages/npm-scripts/src/utils/getMergedConfig.js
=> fix: don't shadow {symbols: 'auto'}

maintenance/projects/js-themes-toolkit-v10-x/packages/bs3-bs4-compat/README.md, maintenance/projects/js-themes-toolkit-v10-x/packages/bs3-bs4-compat/scss/_mixins.scss, projects/js-themes-toolkit/packages/bs3-bs4-compat/README.md, projects/js-themes-toolkit/packages/bs3-bs4-compat/scss/_mixins.scss
=> fix(bs3-bs4-compat): Add lexicon-ux@1.x mixins

projects/js-toolkit/packages/portal-base/src/build/bundler2.ts
=> fix: fix source maps for liferay-npm-bundler v2 builds

third-party/projects/alloy-ui/.alloy.json, third-party/projects/alloy-ui/bower.json, third-party/projects/alloy-ui/package.json
I add this as a pull until we get permissions to push it.
=> chore(alloy-ui): prepare 3.1.0-deprecated.111

projects/js-toolkit/packages/js-api/data-set/index.ts
If this looks good, I will publish and add to portal along with the new CX
=> feat(js-api): add types for FDSFilter client extension

projects/js-themes-toolkit/packages/liferay-theme-tasks/CHANGELOG.md, projects/js-themes-toolkit/packages/liferay-theme-tasks/package.json
This reverts commit b4839e0045af0689f7dd98ffc54b311f3ab3e0be.
=> revert: "chore: prepare liferay-theme-tasks/v11.5.2 release"

projects/npm-tools/packages/npm-scripts/src/typescript/configureTypeScript.js
Had an issue where "overrides" would always show up at the end of the config, meaning it would break portal's SF.
=> fix(npm-scripts): sort tsconfig when generating

projects/js-toolkit/packages/js-api/data-set/index.ts
This is for https://liferay.atlassian.net/browse/LPD-24691
=> feat(js-api): add fieldName as an argument to FDSFilterHTMLElementBuilderArgs
