README.md, projects/eslint-config/README.md
As I've noted in other commits, for now we are just going to run CI over everything in the monorepo. Once that gets too big/slow we will look at making the runs "smarter" (eg. only run on projects which have changes in them).
But for now, given that the run is global, the badge belongs somewhere global too.
=> docs: move CI badge up to top-level README

README.md
With more projects in the monorepo we need good tools for dealing with the increased load on the issue tracker, so that people can focus on what they need to on any given moment.
=> docs: add a table with links to per-project and per-package issue listings

.github/ISSUE_TEMPLATE/changelog-generator.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/eslint-config.md, .github/ISSUE_TEMPLATE/jest-junit-reporter.md, .github/ISSUE_TEMPLATE/js-insights.md, .github/ISSUE_TEMPLATE/js-publish.md, .github/ISSUE_TEMPLATE/npm-bundler-preset-liferay-dev.md, .github/ISSUE_TEMPLATE/npm-scripts.md
As discussed [here](https://github.com/liferay/liferay-frontend-projects/pull/73#issuecomment-698824867).
Note: this won't scale super well once this project has many more packages in it (which will happen as soon as we pull in the js-toolkit), so we may have to revisit this in the future.
We can't have a hierarchical issue template (ie. projects, with issue types as sub-templates), so I have just stuck the type in here as a generic checklist. We can flesh these out more later. Maybe something super generic like:
---
**Desired behavior:**
**Current behavior:**
**Other information (environment, versions etc):**
---
That might cover feature requests, bug reports and questions well enough, even though it is a bit imprecise.
But note that even without hierarchical templates, doing what I've …
=> feat: set up issues templates

.github/ISSUE_TEMPLATE/config.yml
As described [here (see screenshots)](https://github.com/liferay/liferay-frontend-projects/pull/76#issuecomment-698896555), it doesn't seem to be allowed.
Example project using a non-mailto URL:
- https://github.com/node-fetch/node-fetch/issues/new/choose
- https://github.com/node-fetch/node-fetch/blob/master/.github/ISSUE_TEMPLATE/config.yml
Note it is also using `blank_issues_enabled`, but it doesn't seem to make any difference. Clay for example, has the same behavior even without the property. Perhaps it defaults to `true`.
- https://github.com/liferay/clay/issues/new/choose
- https://github.com/liferay/clay/tree/master/.github/ISSUE_TEMPLATE
=> fix: don't use a mailto URL in the issue template configuration

CONTRIBUTING/migrating-an-npm-package-to-the-liferay-named-scope.md, projects/eslint-config/CHANGELOG.md, projects/npm-tools/packages/changelog-generator/CHANGELOG.md, projects/npm-tools/packages/jest-junit-reporter/CHANGELOG.md, projects/npm-tools/packages/js-insights/CHANGELOG.md, projects/npm-tools/packages/js-publish/CHANGELOG.md, projects/npm-tools/packages/npm-bundler-preset-liferay-dev/CHANGELOG.md, projects/npm-tools/packages/npm-scripts/CHANGELOG.md
I couldn't do this when I did the original import, then migrated the packages into named scopes, then did equivalent releases, because we needed [this PR](https://github.com/liferay/liferay-frontend-projects/pull/83) in to teach the changelog-generator to work with the new monorepo structure.
Now we have that, though, I was able to generator the changelogs with these commands:
cd projects/npm-tools/packages/changelog-generator
node bin/liferay-changelog-generator.js --from=liferay-changelog-generator/v1.4.1 --version=1.4.1
cd ../jest-junit-reporter
node ../changelog-generator/bin/liferay-changelog-generator.js --from=liferay-jest-junit-reporter/v1.2.0 --version=1.2.0
cd ../js-insights
node ../changelog-generator/bin/liferay-changelog-generator.js --version=0.0.1
cd ../js-publish
node …
=> docs: update changelogs for imported packages

projects/npm-tools/CONTRIBUTING.md, projects/npm-tools/packages/js-publish/README.md, projects/npm-tools/packages/js-publish/src/index.js
After using this "auto-update-`stable`" behavior for a year now, we've never once needed to go back to `stable` and cut a release from it.
So, let's just jettison it. Now that we've moved to the monorepo it seems like a good opportunity to avoid adding the clutter.
=> feat!(js-publish): don't bother updating stable branch any more

projects/npm-tools/packages/npm-scripts/src/config/jest.config.js
Noticed while running test for https://github.com/liferay-frontend/liferay-portal/pull/409 that we had this straggling reference to the old reporter.
=> fix(scripts): update references to @liferay/jest-junit-reporter

projects/npm-tools/packages/npm-scripts/src/config/npm-bundler.json
But note that, [as described here](https://github.com/liferay/liferay-js-toolkit/pull/654), we are going to need a fix to the bundler because it doesn't currently work with named-scope presets:
=> fix(scripts): remove stale reference to old bundler preset

projects/npm-tools/packages/changelog-generator/README.md
The old repos have been archived (marked read-only) as of today, so we may as well update these links to point at the new locations.
=> docs(changelog-generator): update project links

projects/npm-tools/packages/npm-scripts/package.json
[npm-bundler-preset-liferay-dev release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-bundler-preset-liferay-dev%2Fv4.6.3).
Motivating change is to get [liferay-js-toolkit#654](https://github.com/liferay/liferay-js-toolkit/pull/654) ("fix(common): allow presets that have a named-scope").
Updated with:
cd projects/npm-tools/packages/npm-scripts
yarn add @liferay/npm-bundler-preset-liferay-dev@4.6.3
=> chore(npm-scripts): update npm-bundler-preset-liferay-dev to v4.6.3

support/install-packages.sh
This is a crude script that will almost certainly have to be evolved as the shape and structure of the monorepo evolves, but it works for now with the set of packages that we currently have.
It addresses a bunch of "gotchas" that come with trying to test out packages with local changes in a liferay-portal checkout. Depending on which packages you want to test and the dependency graph between them, you may find that `yarn link` (or even `yarn add`) doesn't do what you want. Even if you manually copy files (`cp`), things still might not work because Gradle may decide to re-run a task that ends up blowing away any changes you make locally under `node_modules`.
At least for the simple case, this script was good enough to allow me to test …
=> feat: add script to install packages locally in a DXP checkout

projects/npm-tools/packages/npm-scripts/README.md
Seeing as we have our first external "client", I think we should give a high-level intro about what the scripts are for, as well as linking to an example of an integration.
Via the "Boy Scout Rule", fixing a capitalization error on the way.
=> docs(scripts): add top-level sinopsis

CONTRIBUTING.md
At this time, this is just a table-of-contents for the other contributing docs in the repo.
As we standardize the procedures across projects, some or all of the project-specific contributing guides will probably go away, but for now, we link to them.
=> docs: add top-level CONTRIBUTING.md

.github/workflows/ci.yml, projects/npm-tools/packages/npm-scripts/src/scripts/format.js
We're not going to change the default globs in liferay-portal yet (or possibly ever?) because the Java Source Formatter currently handles these types.
However, we can make it easier for non-liferay-portal projects like [liferay-learn](https://github.com/liferay/liferay-learn) that use liferay-npm-scripts to run Prettier over a broader range of files. It's a simple matter of expanding the list of allowed globs.
**Test plan:**
In order to actually test this I had these two PRs applied:
- https://github.com/liferay/liferay-frontend-projects/pull/101
- https://github.com/liferay/liferay-frontend-projects/pull/102
Then, with this npmscripts.config.js at the top level of the monorepo:
check: ['**/*.{md,ts,yml}'],
fix: ['**/*.{md,ts,yml}'],
}
I created some bad files and ran …
=> feat(scripts): allow Prettier to format more files (YAML, Markdown)

projects/npm-tools/packages/npm-scripts/src/prettier/index.js
Noticed while testing a PR for [#92](https://github.com/liferay/liferay-frontend-projects/issues/92) that we aren't applying our Liferay-specific Prettier overrides to TS files. ie. we're not enforcing this:
}
else {
**Test plan:**
Add a ".ts" file, "x.ts" with these contents:
if (true) {
alert('t');
} else {
alert('f');
}
Add an "npmscripts.config.js" file (you don't need the ".md" and ".yml" in there, but this is the file I had to create to test the other PR anyway, so I'm just using the same one):
check: ['**/*.{md,ts,yml}'],
fix: ['**/*.{md,ts,yml}'],
}
Run `projects/npm-tools/packages/npm-scripts/bin/liferay-npm-scripts.js check` and see the error reported.
Run `projects/npm-tools/packages/npm-scripts/bin/liferay-npm-scripts.js fix` and see the code fixed to:
if …
=> fix(scripts): apply Liferay-specific Prettier overrides to TS also

package.json, projects/eslint-config/package.json, projects/npm-tools/packages/npm-scripts/package.json, yarn.lock
May as well do this now, as I found it easier to test my solution for [#92](https://github.com/liferay/liferay-frontend-projects/issues/92) with only one version of ESLint in the monorepo (previously we had one version in npm-scripts and another at the top level).
Closes: https://github.com/liferay/liferay-frontend-projects/issues/47
=> chore: update ESLint to latest v7 release

.gitignore
Keep the clutter out of the `git status` output for these files that are all too easy to produce.
=> chore: ignore yarn-error.log files

projects/npm-tools/CONTRIBUTING.md
This one was still pointing at the old repo (which is now archived/read-only) instead of the monorepo.
=> docs(npm-tools): update a stale link

projects/npm-tools/packages/npm-scripts/src/prettier/index.js, projects/npm-tools/packages/npm-scripts/src/prettier/rules/newline-before-block-statements.js, projects/npm-tools/packages/npm-scripts/test/prettier/index.js
So, I thought I had this working in [#101](https://github.com/liferay/liferay-frontend-projects/pull/101) (see the test plan), but when I got this into liferay-portal in [liferay-frontend/liferay-portal#415](https://github.com/liferay-frontend/liferay-portal/pull/415), I found it wasn't working (the `else` formatting wasn't applying). So I made the edits in this PR directly in the node_modules folder to realllllly see it working.
First step: switch in the TS parser when dealing with a TS file.
Second step: observe the same problem we saw (and fixed) in d8b03088be5c76fed — namely, that the TS parser doesn't put `start` and `end` properties on its tokens. We can switch to `range[0]` and `range[1]` respectively, making the rule work with both parsers.
Test plan: manually tested in-place, …
=> fix(npm-tools): make Prettier overrides work with TS

projects/eslint-config/package.json, yarn.lock
This isn't _strictly_ necessary, but it is an accurate description of the requirements of the project. We go with the somewhat unsatisfying range of "*" to to minimize the risk of introducing duplicates in a consuming project. At the moment, we're using v4+ in this monorepo, 3.9.7 in liferay-portal, and the lowest range that we're currently using in any other project is "^3.6.3" (in liferay-js-toolkit). In the future, we should be able to converge on v4+.
If you have a ".ts" file in your project, you are going to have `typescript` in your `devDependencies`, and our `overrides` configuration is going to use `@typescript-eslint/parser`, which in turn is going to require `typescript`, transitively, in `@typescript-eslint/typescript-estree` …
=> chore(eslint-config): mark typescript as a peer dependency

projects/npm-tools/packages/npm-scripts/package.json, yarn.lock
Just a routine update; nothing in here will really makes a visible difference, but seeing as I am about to cut an npm-scripts release, I may as well update to the latest.
[Full release notes for `@liferay/eslint-config` v21.2.1 are here](https://github.com/liferay/liferay-frontend-projects/releases/tag/eslint-config%2Fv21.2.1). Copy-pasting the relevant bits:
-   chore(eslint-config): update eslint-plugin-react to v7.21.3 ([\#115](https://github.com/liferay/liferay-frontend-projects/pull/115))
-   chore(eslint-config): mark typescript as a peer dependency ([\#113](https://github.com/liferay/liferay-frontend-projects/pull/113))
=> chore(npm-scripts): update @liferay/eslint-config to v21.2.1

projects/npm-tools/packages/changelog-generator/src/index.js
This makes the workflow described in [this comment](https://github.com/liferay/liferay-frontend-projects/issues/87#issuecomment-702644789) a bit easier.
Namely, when you are about to cut a release, and you want to preview what will go into the changelog and use that to guide your decision about whether to make this a `--patch`, `--minor` or `--major` (etc) release, you can just run the generator with the `--dry-run` switch, ignoring the usual requirement to pass a `--version`.
Test plan:
1.  Try running the generator without a `--version` and see it complain:
```
changelog-generator ❯ bin/liferay-changelog-generator.js
____________________
(_)                  `
|                  |
|   changelog.js   |
|   ============   |
|                  |
|   Reporting      |
|   for duty!      |
| …
```
=> feat(changelog-generator): make --version optional when --dry-run is on

projects/eslint-config/CONTRIBUTING.md, projects/eslint-config/package.json, projects/npm-tools/CONTRIBUTING.md
A few places where we're telling people to use the last-published version of the changelog-generator (via `npx`) tell them to use `yarn run` instead; this means they'll get the current version in the workspace instead.
About the only time this won't work is if you haven't run `yarn` yet, which I'm not particularly worried about, or you have broken the local copy of the generator (and that's one of the main reasons why we like dog-fooding anyway; to find out when we've broken things).
We also get rid of one `npx` usage in eslint-config's `package.json file. That runs the last-published version of js-publish, but we should instead  directly run the one that we have in the repo (we're already doing this
in the npm-tools packages).
=> docs: encourage people to dog-food local packages

CONTRIBUTING/importing-a-project.md
To avoid any unpleasantness, like accidentally pushing unwanted tags the next time you run `git push` with `--tags` or `--follow-tags`, or the simple annoyance of having to delete dozens or hundreds of tags.
=> docs: advise people to remove the temporary remote after importing

.github/labeler.yml
Anything touching either 2.x or 3.x gets a "js-toolkit" label.
Additionally, we add "2.x" and "3.x" to distinguish the two projects.
(Note that there is no problem with having a "2.x" label eventually being shared by another project, like, say, AlloyEditor, because these projects can always be distinguished by looking at the combination of the version number label and the project name label.)
=> chore: configure labeler for js-toolkit

CONTRIBUTING.md, README.md
I took the liberty of backtick-izing some project names to make them stand out from the version numbers, seeing as js-toolkit is the first project we have here that obliges us to deal with versions.
=> docs(js-toolkit): add links from top-level README and CONTRIBUTING

.editorconfig
In preparing https://github.com/liferay/liferay-frontend-projects/pull/126 I had to edit some ".ts" files by hand, so noticed that we didn't have ".ts" in our editorconfig yet.
=> chore(monorepo): add ".ts" to our editorconfig

maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/copy.ts, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/jar.ts, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/localization.ts, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/misc.ts, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/rules.ts, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/transform.ts, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/util.ts, projects/eslint-config/plugins/liferay/lib/common/imports.js, projects/eslint-config/plugins/liferay/tests/lib/rules/sort-imports.js, projects/js-toolkit/packages/liferay-npm-bundler/src/report/html.ts
I don't like these "." imports as there are not very idiomatic; I guess they're not common because they are subtle and potentially confusing. If you are in a folder and "./index" is the manifest of everything exportable in that folder, then that would normally include the file doing the import, which is circular. So the cognitive load of thinking that through is higher than it need be.
Anyway, even though I don't like them, it doesn't mean I shouldn't fix the bug. So here goes.
Closes: https://github.com/liferay/liferay-frontend-projects/issues/129
=> fix(eslint-config): special case import of "."

maintenance/projects/js-toolkit/lerna.json, projects/js-toolkit/packages/generator-liferay-js/.yarnrc, projects/js-toolkit/packages/liferay-js-toolkit-core/.yarnrc, projects/js-toolkit/packages/liferay-js-toolkit-scripts/.yarnrc, projects/js-toolkit/packages/liferay-npm-bridge-generator/.yarnrc, projects/js-toolkit/packages/liferay-npm-bundler/.yarnrc
- Adjust existing .yarnrc files so that the release commit message matches the format used by other packages in this monorepo.
- Add .yarnrc files for packages that don't have them yet.
- Configure Lerna (still used in v2 of the js-toolkit) to produce commit messages that match the format produced by yarn; previously they produced commit messages consisting just of the bare version number (eg. see b493e109afa2c706ce5fcea79b81a54ac72578d9), which isn't appropriate for a multi-project monorepo.
=> chore(js-toolkit): configure release messages consistently

README.md, maintenance/projects/js-toolkit/CONTRIBUTING.md, maintenance/projects/js-toolkit/README.md
As I want to cut a release (just a patch release, to prove that releasing from the monorepo works, and to update the README and metadata on the package pages on the npm registry) I'm just sweeping through and updating links and other information that needs to be tweaked now that we're in the monorepo.
The one link I didn't update was the link to the wiki, because we haven't migrated that yet (we still need to decide whether to migrate it, or whether to move the contents into a `docs/` folder).
For consistency, snuck in one edit to the top-level README to make sure we use the same alt text on our CI badges everywhere.
=> docs(js-toolkit): update links prior to release

CONTRIBUTING/importing-a-project.md, maintenance/projects/js-toolkit/CONTRIBUTING.md, maintenance/projects/js-toolkit/lerna.json
Just some small changes to reflect what I learned while doing our first release of the v2.x series from the monorepo context.
As a bonus, you get a free set of Conventional Commits types!
- "chore" to describe the overall feeling I had when preparing this PR.
- "fix" because the Lerna config was wrong.
- "docs" because I edited docs.
- "style" because Lerna seemed to mess up the formatting during publish, so I had to run `yarn format`.
=> chore(js-toolkit): make post-release tweaks

projects/npm-tools/packages/npm-scripts/package.json
[Release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-bundler-preset-liferay-dev%2Fv4.6.4)
This is really just an integration test to make sure that we can release v2.x js-toolkit packages from the monorepo.
Updated with:
cd projects/npm-tools/packages/npm-scripts
yarn add @liferay/npm-bundler-preset-liferay-dev@4.6.4
=> chore(npm-scripts): update npm-bundler-preset-liferay-dev to v4.6.4

.mailmap
My OCD compels me to do this. It enables Git to dedupe authors that have created commits with multiple email addresses or name variations.
Before - 40 "unique authors":
git shortlog -s -e | cut -f 2 | wc -l
40
After - 27 unique authors:
git shortlog -s -e | cut -f 2 | wc -l
27
=> chore(monorepo): add a .mailmap file

projects/js-toolkit/packages/generator-js/CHANGELOG.md, projects/js-toolkit/packages/js-toolkit-core/CHANGELOG.md, projects/js-toolkit/packages/js-toolkit-scripts/CHANGELOG.md, projects/js-toolkit/packages/npm-bridge-generator/CHANGELOG.md, projects/js-toolkit/packages/npm-bundler/CHANGELOG.md
As these first releases under the `@liferay` named scope are all a bit manual and weird, I'm batching the (basically manual) updates for all the packages into this one commit. Note that there were a couple of packages there that we never officially released, so they get CHANGELOG files for the first time. (We may not end up continuing to release those packages in the future — they may get refactored and cease to exist independently — but in the short term we want to respect the "Principle of Least Surprise" and ensure that everything under `packages` in the monorepo is both publishable and published, even if only as an ephemeral prerelease).
Other than that, these packages should all be basically identical to the non-named-scope cousins with the same version number. Only the names have …
=> docs(js-tookit): update CHANGELOG files for first named scope releases

projects/js-toolkit/packages/generator-js/package.json, projects/js-toolkit/packages/js-toolkit-core/package.json, projects/js-toolkit/packages/js-toolkit-scripts/package.json, projects/js-toolkit/packages/npm-bridge-generator/package.json, projects/js-toolkit/packages/npm-bundler/package.json, projects/js-toolkit/packages/npm-bundler/src/bundle/configure.ts, projects/js-toolkit/packages/npm-bundler/src/globals.ts
Fixes the issues discovered in https://github.com/liferay-frontend/liferay-portal/pull/429
See individual commit messages for explanations.
=> fix(js-toolkit): fix various integration problems with DXP

projects/js-toolkit/.yarnrc, projects/js-toolkit/CONTRIBUTING.md
This was originally going to be a "docs" type task to update this doc to rectify the staleness that I discovered while doing our first `yarn version`-powered releases of js-toolkit packages in the `@liferay/` named scope today:
- https://github.com/liferay/liferay-frontend-projects/releases/tag/js-toolkit-core%2Fv3.0.1-pre.0
- https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-bundler%2Fv3.0.1-pre.0
In the end, though, going with "chore" because I also had to strip out some misleading config in the .yarnrc. The `--publish.tag` config is never going to be used, because now that we are on the `master` branch, we will use `@liferay/js-publish` just like any other project, which means you release by running `yarn version`, not `yarn publish`. And `@liferay/js-publish` sets …
=> chore(js-toolkit): update release process docs and configuration

projects/js-toolkit/CONTRIBUTING.md
Missed this one when I updated the docs in https://github.com/liferay/liferay-frontend-projects/pull/158
=> docs(js-toolkit): remove another stale line from the documentation

projects/js-toolkit/packages/npm-bundler/src/bundle/configure.ts
In the fragments toolkit, webpack will get a relative path of the form:
build/liferay-npm-bundler-workdir/generated/sample-fragment.js
(via: https://github.com/liferay/generator-liferay-fragments/pull/167)
In DXP, we get a path of the form:
$ABSOLUTE_PATH_TO_REPO_ROOT/modules/apps/frontend-js/frontend-js-recharts/build/node/bundler/bundler/generated/recharts.js
(via: https://github.com/liferay-frontend/liferay-portal/pull/429)
Unfortunately, webpack is fussy and won't accept the first form, demanding instead the `./` prefix; ie:
./build/liferay-npm-bundler-workdir/generated/sample-fragment.js
This means that the fix we applied in c204ca06ac3a982a1ca353b8652f9c71 unbreaks DXP at the expense of breaking the fragments toolkit.
So here, we add a ternary to handle both cases. Note that we have …
=> fix(js-toolkit): unbreak fragments toolkit

projects/npm-tools/packages/changelog-generator/src/console.js, projects/npm-tools/packages/changelog-generator/src/git.js, projects/npm-tools/packages/changelog-generator/src/index.js, projects/npm-tools/packages/changelog-generator/src/matchOption.js, projects/npm-tools/packages/changelog-generator/src/printBanner.js, projects/npm-tools/packages/changelog-generator/src/readYarnrc.js
Still a draft because I want to refactor this to clean it up.
But in short, what this gives us is a set of new options:
- `--major`
- `--minor`
- `--patch`
- `--premajor`
- `--preminor`
- `--prepatch`
- `--prerelease`
- `--preid`
That match the options and behavior of the corresponding `yarn` ones.
These can be used to make the release process for most packages look like this:
npx @liferay/changelog-generator --dry-run  # preview changes, decide on release type
npx @liferay/changelog-generator --patch    # actually generate changes
git add -p                                  # stage changes
yarn version --patch                        # do release
And then on top of that, I added another switch:
- `--interactive`/`-i`
That turns the release process into this:
npx …
=> feat(changelog-generator): add --major, --minor etc convenience switches

projects/amd-loader/.gitignore
Because this one is covered by the top-level one in the root of the monorepo.
=> chore(amd-loader): remove an unnecessary line from the .gitignore

projects/amd-loader/package.json
Will use this to make one last non-named-scope release, and then [a named-scope one](https://github.com/liferay/liferay-frontend-projects/pull/200) after that.
=> chore(amd-loader): prepare for releases via js-publish

projects/amd-loader/CHANGELOG.md
This project has never had an in-repo changelog, so we generate one from scratch:
git checkout 17a5ab58
npx @liferay/changelog-generator --regenerate --minor
git checkout master
mv CHANGELOG.md projects/amd-loader
git add projects/amd-loader/CHANGELOG.md
So, two or three oddities to note here:
- The use of `--minor` is arbirtrary; I just needed to pick a version that was above the previously released one. The changes that have been made since that last release get stripped out by hand and will be included in the next release.
- Given that the changelog generator relies on the `--first-parent` switch, I checked out 17a5ab58 because that is a commit that predates the subtree merge; it means we can look at the history from the perspective of what the project used to look like in the old …
=> docs(amd-loader): add changelog

maintenance/projects/js-toolkit/docs/How-to-create-mixed-Java-JavaScript-projects.md, maintenance/projects/js-toolkit/docs/How-to-deploy-npm-packages-to-Liferay.md, maintenance/projects/js-toolkit/docs/How-to-use-liferay-npm-bundler.md, projects/amd-loader/package.json, projects/js-toolkit/packages/npm-bundler/src/liferay-npm-bundler.config.ts, projects/npm-tools/packages/npm-bundler-preset-liferay-dev/config.json
This is going to be one of the simpler projects to move, as far as I can tell, because:
- I already named the directory "amd-loader" instead of "liferay-amd-loader" when I imported the history.
- The autolabeler is already set up to use the "amd-loader" label for that directory.
- The .yarnrc file is already set up to assume the new name.
But note that we must touch two other projects in this commit:
- The preset needs to know about the new name and version.
- The toolkit needs to know for the same reason.
- We update some docs.
One of the nice things about the monorepo is that we can make an atomic commit like this that touches three projects in a single change. I believe all this is safe because the changes to the loader are all safe (ie. backportable), which means that in turn the …
=> chore(amd-loader): prepare to release under @liferay named scope

projects/amd-loader/CONTRIBUTING.md, projects/eslint-config/CONTRIBUTING.md, projects/js-toolkit/CONTRIBUTING.md, projects/npm-tools/CONTRIBUTING.md
- Added one for amd-loader because it didn't have one.
- Recommend the use of the new `--interactive` switch to `@liferay/changelog-generator`.
- Tweak the js-toolkit one to reflect our monorepo-wide commit conventions.
One small thing to note: in the amd-loader document I refer to the project as `@liferay/amd-loader` because we're about to migrate it into the named scope and we may as well skate towards where the puck is going.
=> docs(monorepo): make CONTRIBUTING.md docs more consistent

CONTRIBUTING/migrating-an-npm-package-to-the-liferay-named-scope.md
Seeing as I just had to use it like this, documenting it for posterity.
=> docs(monorepo): add example of using version range with `npm deprecate`

projects/amd-loader/package.json, projects/eslint-config/package.json, projects/js-toolkit/package.json, projects/npm-tools/package.json, projects/npm-tools/packages/npm-scripts/package.json
The idea is that when you run `yarn ci` from anywhere in the repo we run all the tests in the repo to make sure that everything works well together, but when you are inside a project or a package directory, you can run `yarn test` to run only the tests for that package and get a quicker feedback loop. Running `yarn test` at the top level continues to run everything. Running it at an intermediate level, like say, "projects/npm-tools/" will run it for all the packages nested below that point.
=> test(monorepo): consistently run local tests scoped to project/package

projects/npm-tools/packages/changelog-generator/bin/liferay-changelog-generator.js, projects/npm-tools/packages/changelog-generator/package.json, projects/npm-tools/packages/changelog-generator/src/index.js, projects/npm-tools/packages/changelog-generator/src/readYarnrc.js, projects/npm-tools/packages/changelog-generator/test/index.js
So I noticed while preparing the 3.0.1 release of the npm-bundler that we had a discrepancy between how we determine the next version number and how Yarn does it.
Namely:
- We were at 3.0.1-pre.1.
- We ran `yarn run liferay-changelog-generator -i` and selected a "patch" release; that bumped the version number to 3.0.2 in the changelog.
- We then ran `yarn version --patch` and that bumped the version number to 3.0.1 in the package.json; you can see both of those changes in 113b7addc894.
- We then fixed the mismatching number by editing the changelog in 54b66db412b8.
So, I went back and ran `yarn version` in a test project in a bunch of combinations and observed the behavior. Added some tests to show what the expected behavior is (the list of combinations is long so I won't repeat it here, …
=> fix(changelog-generator): match `yarn version` behavior more closely

projects/npm-tools/packages/js-publish/src/index.js
So, we added this check in a58c811125b, with the explanation that we wanted to make the publish script "more suitable for generic use". And if you look at the README in the parent commit, 7bd58103889, you see that our intent was that the user set up a `postversion` script that just called `npx liferay-js-publish`.
Fair enough, so that meant a somewhat loose substring check of:
includes('liferay-js-publish')
When we moved the package into a named scope in 63222b948b1, we switched over to this regexp-based check:
match(/(?:\bliferay-js-publish|@liferay\/js-publish)\b/)
Now, with the introduction of liferay-workspace-scripts, we'd need to add another possibility to that pattern, which would lead us to this monstrosity:
match(/(?:@liferay\/js-publish|\bliferay-js-publish|\bliferay-workspace-sc …
=> refactor(js-publish): make package check less strict

projects/js-toolkit/packages/js-toolkit-scripts/package.json, projects/js-toolkit/packages/npm-bridge-generator/package.json, projects/js-toolkit/packages/npm-bundler/package.json
It is not mandatory, but after the failed PR at https://github.com/liferay/liferay-frontend-projects/pull/218 we have decided to merge at least this change.
=> refactor: prepend './' to binary scripts path

maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/__tests__/manifest.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/manifest.ts
Hello there :-)
This small PR solves a problem with version numbers having a qualifier.
None of these version numbers work:
```json
{
"version": "7.12.0-clavis-17"
}
```
```json
{
"version": "7.12.0.clavis-17"
}
```
***`7.12.0-clavis-17`***
1. `yarn run build` works
2. The jar gets created
3. The `MANIFEST.MF` contains the `Bundle-Version: 7.12.0-clavis-17`
4. OSGi-Deployment fails because of an OSGi-incompatible version number
```
INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:271] Processing xxx-7.12.0-clavis-17.jar
[...]
java.lang.IllegalArgumentException: invalid version "7.12.0-clavis-17": non-numeric "0-clavis-17"
[...]
```
***`7.12.0.clavis-17`***
1. Building fails because of an npm-incompatible version number
```bash
$ yarn run build
[...]
Error: …
```
=> feat(js-toolkit): convert package.json version classfier to OSGi version classifer

maintenance/projects/js-toolkit/CHANGELOG.md
This cruft was in there because [we generate changelog messages by extracting the body from our merge commits](https://github.com/liferay/liferay-frontend-projects/blob/8c6cc33e718ac2f2bcd233d7310a72ffa2cd4785/projects/npm-tools/packages/changelog-generator/src/index.js#L172-L181). Normally, that works, because it means pulling in the pull request titles from merge commits that GitHub generates which look like this:
commit db37808ad9c250ccd2511232d07d197b8c259cf9
Merge: 35d260aa a12566f6
Author: Iván Zaera Avellón <ivan.zaera@liferay.com>
Date:   Fri Nov 6 13:18:59 2020 +0100
Merge pull request #227 from izaera/issue-226
feat: upgrade sample project to Angular 10
(ie. "feat: upgrade sample project to Angular 10" is extracted)
But in this case, it pulled in a rare manual merge that I made …
=> docs(js-toolkit): clean some cruft out of changelog

projects/npm-tools/packages/npm-scripts/src/jest/setup.js
This PR has a handful of failing unit tests due to createRange not existing in js-dom. Rather than add a setupfile for each module to include this, I figured its best to have as a global mock.
https://github.com/liferay-frontend/liferay-portal/pull/468
=> feat(npm-scripts): add jest mock for createRange and createContextualFragment

.github/workflows/ci.yml
This should ensure that we don't run into the kind of issue [mentioned here](https://github.com/liferay/liferay-frontend-projects/pull/233#issuecomment-727938944).
Note that `--frozen-lockfile` is supposed to take care of this for us, but it is [a known issue](https://github.com/yarnpkg/yarn/issues/5840) that it doesn't work properly in monorepos. There is [a fix for it](https://github.com/yarnpkg/yarn/pull/6554), but the issue is nearly two years old and the PR is almost as old. Maintainer [replies here](https://github.com/yarnpkg/yarn/pull/6554#issuecomment-532667774) that:
> The change appears sound, but we're currently working on the v2 (scheduled before the end of the year) and I'm somewhat worried about introducing subtle bugs right before releasing the next major (the way I see it, …
=> feat(monorepo): complain if lockfile is not fresh

projects/npm-tools/packages/npm-scripts/package.json, projects/npm-tools/packages/npm-scripts/src/config/terser.config.js, projects/npm-tools/packages/npm-scripts/src/index.js, projects/npm-tools/packages/npm-scripts/src/jsp/README.md, projects/npm-tools/packages/npm-scripts/src/jsp/formatJSP.js, projects/npm-tools/packages/npm-scripts/src/jsp/lintJSP.js, projects/npm-tools/packages/npm-scripts/src/jsp/padLines.js, projects/npm-tools/packages/npm-scripts/src/jsp/processJSP.js, projects/npm-tools/packages/npm-scripts/src/presets/standard/index.js, projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/src/scripts/format.js, projects/npm-tools/packages/npm-scripts/src/scripts/prettier.js, projects/npm-tools/packages/npm-scripts/src/utils/getMergedConfig.js, projects/npm-tools/packages/npm-scripts/src/utils/getPaths.js, projects/npm-tools/packages/npm-scripts/src/utils/minify.js, projects/npm-tools/packages/npm-scripts/test/jsp/formatJSP.js, projects/npm-tools/packages/npm-scripts/test/jsp/lintJSP.js, projects/npm-tools/packages/npm-scripts/test/jsp/padLines.js, projects/npm-tools/packages/npm-scripts/test/jsp/processJSP.js, projects/npm-tools/packages/npm-scripts/test/prettier/index.js, projects/npm-tools/packages/npm-scripts/test/scripts/format.js, projects/npm-tools/packages/npm-scripts/test/utils/minify.js, yarn.lock
~This is a far-from-finished WIP, but parking it here anyway for safe-keeping:~ (upgrading this from WIP to POC)
Final status:
-    [Discussed in Slack here](https://liferay.slack.com/archives/C04D8HMEF/p1606233408059000):
-   The JS-in-JSP minification works if you run `yarn build` by hand, but when run as part of a `gradle` invocation the jobs happen in the wrong order for our purposes — we can't minify the JS in JSP in `classes/` because it only gets put there _after_ `packageRunBuild`. The conclusion of the Slack thread is that we can leave the code in here as a kind of benign no-op, and if we decide to prioritize the necessary changes on the Gradle side it will "magically" start working. If it's still there months from now and it looks like we're never going to get to it we can just …
=> feat(npm-scripts): add minification to build process

projects/npm-tools/packages/npm-scripts/src/config/stylelint.json
Came up in [this Slack thread](https://liferay.slack.com/archives/CNBG06JS3/p1606416319333100).
We decided to add the `at-rule-no-unknown` rule [here](https://github.com/liferay/liferay-npm-tools/issues/344#issuecomment-576756682) and customized the whitelist of allowed rules [here](https://github.com/liferay/liferay-npm-tools/pull/347/commits/be48c275d5377a1b1f1a0cb34a37a1c807c1846c) based on the built-in rules that come with Sass and that were currently in use in DXP at the time.
@eduardoallegrini [says](https://liferay.slack.com/archives/CNBG06JS3/p1606466305337500?thread_ts=1606416319.333100&cid=CNBG06JS3) that `@function` is kosher to add to the list, although the truth is we may not need it in many places. Right now `master` has exactly one usage and one corresponding lint …
=> feat(npm-scripts): add `@function` and `@return` to list of stylelint at-rules

projects/npm-tools/packages/npm-scripts/src/index.js
This was causing an unhandled rejection when the build process failed, which led to gradle not noticing any problem and continuing as if nothing had happened.
=> fix(npm-scripts): avoid unhandled promise rejection

projects/npm-tools/packages/npm-scripts/src/jsp/padLines.js, projects/npm-tools/packages/npm-scripts/src/utils/minify.js, projects/npm-tools/packages/npm-scripts/test/jsp/padLines.js, projects/npm-tools/packages/npm-scripts/test/utils/minify.js
Just testing the [claim made in this Slack thread](https://liferay.slack.com/archives/C04D8HMEF/p1606323974062700?thread_ts=1606233408.059000&cid=C04D8HMEF) that the reason why my earlier attempts to minify-in-place inside "build/" may have seemed to not be working due to Gradle caching.
While the cache may cause problems, I am skeptical that this will work because in my testing I found that `processResources` happens too late (after `npm-scripts` runs), but in the interests of thoroughness I am going to try this out and test it in a full `ant all` run anyway.
---
Final summary: we tested this out and the minify-in-`build/` trick does work, but even with minification turned way down to avoid reordering issues, testing in DXP shows that it is too risky to turn on by default (for example, …
=> fix(npm-scripts): provide (inactive-by-default) tooling for formatting JS in JSP inside build

CONTRIBUTING/importing-a-project.md
While doing the subtree merge of the liferay-js-themes-toolkit history noticed these small errors, so fixing them now.
=> docs(monorepo): fix minor typos

maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/index.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/manifest.ts, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/osgi.js
Follow-up to PR #219
This PR also converts the version in the manifest header `RequireCapability`.
=> feat(js-toolkit): RequireCapability: convert package.json version classfier to OSGi version classifer

maintenance/projects/js-toolkit/lerna.json
Because [Lerna mangles it](https://github.com/liferay/liferay-frontend-projects/runs/1523806083?check_suite_focus=true) whenever we release.
We're going to have to figure out a way to stop it from doing that... or we might simply hope to stop using Lerna or releasing "legacy" projects which use it... (We could ignore the file, but that defeats the purpose of having Prettier *in charge* of formatting everything in the repo.)
=> style(js-toolkit): fix formatting

projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/src/scripts/webpack.js, projects/npm-tools/packages/npm-scripts/src/utils/tweakWebpackConfig.js
This PR adds newer features to `npm-scripts` which are needed to implement [LPS-124287](https://issues.liferay.com/browse/LPS-124287).
I have tested it locally with the LPS-124287 PR for portal and everything work, but we need to merge this and release a new version for the other PR to work.
=> feat: extend webpack federation support

maintenance/projects/js-themes-toolkit-v8-x/CONTRIBUTING.md, maintenance/projects/js-themes-toolkit-v8-x/README.md, maintenance/projects/js-themes-toolkit-v9-x/CONTRIBUTING.md, maintenance/projects/js-themes-toolkit-v9-x/README.md, maintenance/projects/js-themes-toolkit-v9-x/packages/generator-liferay-theme/lib/util.js, projects/js-themes-toolkit/CONTRIBUTING.md, projects/js-themes-toolkit/README.md
Labeling this as "docs" although there is one code change in there. This commit updates all references that were pointing at the old (archived, read-only) repo to point at the monorepo instead.
Bonus: soft-wrapped the v8 CONTRIBUTING.md because that's what we're doing in all the other Markdown files.
=> docs(js-themes-toolkit): update links to point at new repo

maintenance/projects/js-themes-toolkit-v8-x/package.json, maintenance/projects/js-themes-toolkit-v8-x/packages/generator-liferay-theme/generators/app/__tests__/index.test.js, maintenance/projects/js-themes-toolkit-v8-x/packages/generator-liferay-theme/package.json, maintenance/projects/js-themes-toolkit-v8-x/packages/liferay-theme-deps-7.0/package.json, maintenance/projects/js-themes-toolkit-v8-x/packages/liferay-theme-deps-7.1/package.json, maintenance/projects/js-themes-toolkit-v8-x/packages/liferay-theme-tasks/package.json, maintenance/projects/js-themes-toolkit-v8-x/yarn.lock
This is fiddly, so I did this in small steps in order to document the checks I performed at each step (see commit messages). I'll probably come back to bb2d227 in the future to remind myself of the state of our gulp-sass/node-sass deps.
=> chore(js-themes-toolkit): hoist v8 devDependencies to workspace root

maintenance/projects/js-themes-toolkit-v9-x/package.json, maintenance/projects/js-themes-toolkit-v9-x/packages/generator-liferay-theme/package.json, maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/package.json, maintenance/projects/js-themes-toolkit-v9-x/yarn.lock
Companion pull to https://github.com/liferay/liferay-frontend-projects/pull/285 but for v9 of the toolkit.
This one a bit simpler than that one, with only one extra thing to do (see second commit; we have liferay-frontend-theme `devDependencies` this time).
=> chore(js-themes-toolkit): hoist v9 devDependencies to workspace root

projects/js-themes-toolkit/package.json
Silences:
warning Missing name in workspace at "projects/js-themes-toolkit", ignoring.
=> fix(js-themes-toolkit): silence noisy yarn warning

maintenance/projects/js-toolkit/docs/.npmbundlerrc-file-reference.md, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/jar.ts, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/index.js
( See issue #256 )
We should allow user define the compression level to use when creating the JAR file. By default we are using STORE compression, which doesn't compress anything but this leads to huge JARs and some customers have problems with cloud deployments (see [LPP-39585](https://issues.liferay.com/browse/LPP-39585)).
We should probably use compression level 6 (a compromise between compression speed and artifact size) by default and let the value be configurable in case someone wants to tweak it further.
=> fix(js-toolkit): let compression level be configured

maintenance/projects/js-themes-toolkit-v8-x/.yarnrc, maintenance/projects/js-themes-toolkit-v8-x/CONTRIBUTING.md, maintenance/projects/js-themes-toolkit-v8-x/package.json, maintenance/projects/js-themes-toolkit-v9-x/.yarnrc, maintenance/projects/js-themes-toolkit-v9-x/CONTRIBUTING.md, maintenance/projects/js-themes-toolkit-v9-x/package.json
I'm just running through the CONTRIBUTING.md docs to prove that we can actually do releases from the monorepo, and this commit makes the changes I've identified as being necessary:
- Namely, we need to add a `version-tag-prefix` in the `.yarnrc` files for use by the changelog-generator.
- We need to switch to the latest not-yet-published version of the generator, because the last-published version doesn't want to run from subdirectories like these maintenance projects use (it expects to run from the repo root, or from a packages/ subdirectory).
- In order to distinguish between the two series, we need them to use distinct tag prefixes. We could teach the changelog-generator a new switch to deal with this, but I'd rather not add the complexity there for what is a decidedly odd use case …
=> chore(js-themes-toolkit): make final tweaks for monorepo releases

yarn.lock
Just this noisy little change that came up during the releases:
- https://github.com/liferay/liferay-frontend-projects/releases/tag/generator-liferay-theme%2Fv10.0.2
- https://github.com/liferay/liferay-frontend-projects/releases/tag/liferay-theme-tasks%2Fv10.0.3
CI will complain until this goes in. Example complaint:
https://github.com/liferay/liferay-frontend-projects/actions/runs/421524069
=> chore(monorepo): freshen lockfile

maintenance/projects/js-toolkit/scripts/publish.sh
Added `set -e` to abort at the first sign of things going wrong, seeing as this commit involves pushing semi-blindly to the remote...
I inverted the sense of the remote check so that I could do the publishing + post-publish-fixing in a DRY way (and without having to stick it in a function).
Closes: https://github.com/liferay/liferay-frontend-projects/issues/293
=> feat(js-toolkit): teach publish.sh to revert unwanted formatting changes

maintenance/projects/js-toolkit/lerna.json, projects/js-toolkit/packages/js-toolkit-core/src/transform/js/index.ts, projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/src/scripts/createBridges.js
This is implementation of #290 . Needed for [this portal PR](https://github.com/liferay-frontend/liferay-portal/pull/606).
I have tested it locally and it's not horrible.
--- 
What this basically does is adding a new section inside `federation` of `npmscripts.config.js` containing the packages to bridge. So, for example, if we had this in `frontend-js-react-web`'s `npmscripts.config.js`:
```javascript
federation: {
bridges: {
'classnames': '__classnames',
'formik': '__formik',
'prop-types': '__propTypes',
'react': '__react',
'react-dnd': '__reactDnd',
'react-dnd-html5-backend': '__reactDndHtml5Backend',
'react-dom': '__reactDom'
},
main: 'js/index.federation.js',
}
};
```
It would create bridges from `classnames` in the AMD loader to `classnames` in the webpack realm. …
=> feat: support generation of bridges from AMD to webpack

projects/npm-tools/packages/npm-scripts/src/scripts/createBridges.js
I thought using liferay-js-toolkit-core for namespacing would have done this, but it turns out that [it is done at the bundler level](https://github.com/liferay/liferay-frontend-projects/blob/2da0f09cc0c885db457f4237bd1ac0b432c92bf4/projects/js-toolkit/packages/npm-bundler/src/adapt/bundler-project/write-export-modules.ts#L44), so we have to mimic it here.
I'm not releasing yet, because I have spotted a new error in the [portal's PR](https://github.com/liferay-frontend/liferay-portal/pull/606) :-(
=> fix(npm-scripts): support scoped packages correctly

maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/__tests__/manifest.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/manifest.ts
See [LPP-39704](https://issues.liferay.com/browse/LPP-39704)
=> fix(js-toolkit): unable to deploy to 7.1 due to InvalidSyntaxException

projects/js-themes-toolkit/packages/liferay-theme-tasks/theme/__tests__/index.test.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/theme/index.js
As discussed in [the issue](https://github.com/liferay/liferay-frontend-projects/issues/249), we already have a copy of the liferay-r2 code originally hosted at [liferay-labs/R2](https://github.com/liferay-labs/R2), which got inlined into the themes toolkit in [this commit](https://github.com/liferay/liferay-js-themes-toolkit/commit/a843516ffb18bbeb9b3c3b1c7de8a2622d233b12#diff-a016e05e9164926c610083bf8d96c2a4d473221ecda45c00522bdef0c5d97585).
So, given that we needed access to r2's functionality in [this PR](https://github.com/liferay/liferay-frontend-projects/pull/282), we can just leverage the existing copy of the code that we have in the
theme tasks (npm-scripts already depends on the theme tasks).
Note that I added a couple of simple tests to show that you can actually grab and use …
=> feat(js-themes-toolkit): expose r2 API

.eslintignore, .prettierignore, maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/lib/r2/liferay-r2/.eslintrc.js, maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/lib/r2/liferay-r2/__tests__/index.test.js, maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/lib/r2/liferay-r2/copyright.js, maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/lib/r2/liferay-r2/index.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/.eslintrc.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/__tests__/index.test.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/copyright.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/index.js
As noted here:
- https://github.com/liferay/liferay-frontend-projects/issues/249#issuecomment-733010877
- https://github.com/liferay/liferay-js-themes-toolkit/pull/424#discussion_r368860354
We dropped some licensing information when we forked this package from [ded/R2](https://github.com/ded/R2) into [liferay-labs/R2](https://github.com/liferay-labs/R2). We later [inlined the code into the themes toolkit](https://github.com/liferay/liferay-js-themes-toolkit/commit/a843516ffb18bbeb9b3c3b1c7de8a2622d233b12), and did not restore the original copyright.
Seeing as we were looking at this code for [issue #249](https://github.com/liferay/liferay-frontend-projects/issues/249), we may as well put things right now.
Basically, there are only two files of interest in the original implementation (the …
=> chore(js-themes-toolkit): restore missing license information

.github/ISSUE_TEMPLATE/devDependency.md, README.md
We were using "dev-dependency" over in [the old repo](https://github.com/liferay/liferay-frontend-guidelines) but every time dependabot opens a PR with us it's going to spammily recreate a "dependencies" label, so we may as well just use that one.
=> chore(monorepo): use "dependencies" label instead of "dev-dependency"

.github/labeler.yml
Any change to an "*.md" file is labeled as "docs". Additionally, changes under "guidelines/" are special-cased to reflect that they are meta-documentation about how we do development.
=> chore: set up autolabeling of "docs" and "guidelines" changes

.github/workflows/global.yml, .github/workflows/guidelines.yml, .github/workflows/js-themes-toolkit-v8-x.yml, .github/workflows/js-themes-toolkit-v9-x.yml, .github/workflows/js-toolkit-v2.yml
Before:
-   `ci.yml`:
-   Runs repo-wide lint and formatting checks.
-   Runs tests for all four groups of yarn workspaces, corresponding to:
-   `yarn.lock` (ie. everything under `projects/` on Linux and Windows).
-   `maintenance/projects/js-themes-toolkit-v8-x/yarn.lock`
-   `maintenance/projects/js-themes-toolkit-v9-x/yarn.lock`
-   `maintenance/projects/js-toolkit/yarn.lock`
-   Checks top-level `yarn.lock` only for unwanted changes during installation.
-   `guidelines.yml`: runs checks specific to "guidelines/" directory (specifically, broken-link checks).
-   `labeler.yml`: applies labels automatically based on paths touched by a PR.
After:
-   `guidelines.yml` and `labeler.yml`: same as before.
-   Split `ci.yml` into four files, one corresponding to each group of yarn workspaces: …
=> refactor(monorepo): split GitHub workflows by Yarn workspaces

projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/project/options.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/package.json, projects/js-themes-toolkit/packages/liferay-theme-tasks/theme/tasks/build/index.js, yarn.lock
Hey @bryceosterhaus, @wincent, my gulp fu is pretty rusty (or my fu in general), but I think this should do it as far as minifying JS in themes goes.
> In production mode, `terser` will be invoked to minify `js` resources in a theme after every other processing has taken place.
>
> Terser options can be overriden by declaring a `terser` object in the `package.json` file of your theme. By default, it is invoked with defaults configuration.
>
> Sourcemaps are enabled by default and handled outside of terser if the minification takes place.
Everytime I get back to this I get an intense urge of rewriting the whole thing, but instead, I end up adding yet another thing. One day, though...
=> feat(js-themes-toolkit): adds js minification step (Fixes #364)

guidelines/support/checkLinks.js
This mitigates but does not fix [#360](https://github.com/liferay/liferay-frontend-projects/issues/360).
At this point we see a reliable pattern of npmjs servers rate-limiting us with [HTTP 429 "Too Many Requests" status codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).
Seeing as these links are not definitely broken (ie. they're just not provably correct) we should treat them as soft warnings (even if no one reads them) instead of hard errors.
We can still look at doing something fancy in the future to properly deal with #360, but the present change is cheap and stops the bleeding.
=> feat(guidelines): mitigate problems with link checker rate limiting

.github/workflows/guidelines.yml
So it will show up as "guidelines/check-links" instead of "guidelines/build" (which is a bit misleading. All the other jobs have more accurate/descriptive names, like "check-lockfile", "format-check" and so on, so this just brings this workflow into line with the others.
=> refactor(guidelines): use a better name for CI job

projects/npm-tools/packages/npm-scripts/src/utils/createBridges.js, projects/npm-tools/packages/npm-scripts/src/utils/createFederationConfig.js
This is like reverting to version 36.2.0 but without removing the code, so that we leave `liferay-portal` build in a stable situation for further development.
The code being removed was necessary for [LPS-124287](https://issues.liferay.com/browse/LPS-124287) but given that it won't make it into portal until a new webpack release is made, we are removing this code until then.
The serve side counterpart of this PR is [here](https://github.com/liferay-frontend/liferay-portal/pull/660)
=> fix: stabilize liferay-portal build until a new webpack release arrives

projects/npm-tools/packages/npm-scripts/package.json, projects/npm-tools/packages/npm-scripts/src/transform/js/relocateImports.js, projects/npm-tools/packages/npm-scripts/src/utils/createFederationConfig.js, yarn.lock
See [IFI-2310](https://issues.liferay.com/browse/IFI-2310).
The changes here are needed to build and deploy [this branch](https://github.com/izaera/liferay-portal/tree/LPS-125746).
I will release a new version of `npm-scripts` after this is merged which, BTW, should be the last that we need unless we add new features or fix bugs, because I have added all information contained in the old default preset (see [this commit](https://github.com/liferay/liferay-frontend-projects/commit/c380ba0e1fb1e4f8c3b9e168a7d3b1b667eb75cd)) given that it doesn't fail the build. In addition, it has been made extensible, so..., that should be enough.
As always this has been tested locally with the linked private branch of `liferay-portal`.
I will send the portal's PR as soon as we release a new version of …
=> feat: provide a mechanism to extend the `remotes` and `shared` fields of webpack config

projects/npm-tools/packages/npm-scripts/src/utils/createFederationConfig.js
This is needed for LPS-126503 because we need to export JS endpoint to be consumed from `<react:component>`.
I've tested this locally.
=> feat: allow extension of webpack `exposes`

projects/eslint-config/plugins/portal/docs/rules/deprecation.md, projects/eslint-config/plugins/portal/lib/rules/deprecation.js, projects/eslint-config/plugins/portal/tests/lib/rules/deprecation.js
Fixes #388 
It adds `Cavanaugh (7.4.x)` to the list of possible deprecation versions, adds it to the docs, and adds it to the test.
I ran `yarn ci` and it was green, as all CI's should be.
I didn't mess around with the versioning thing, as I saw some other changes were in the list, if I needed to do that LMK so I can do it.
=> feat(eslint-config): add Cavanaugh 7.4.x to list of possible deprecations

CONTRIBUTING.md, guidelines/README.md
Based on [conversation here](https://github.com/liferay/liferay-frontend-projects/pull/389#issuecomment-770646774) which was about not finding contributing guidelines for how to format commit messages.
We could still use some more specific docs about what scopes we'd like to see when working in the monorepo (eg. using scopes to indicate project), so I added that in the second commit.
=> docs: link to general guidelines and list recommended scopes

guidelines/dxp/linting.md
Seeing as [this came up in code review over here](https://github.com/liferay-frontend/liferay-portal/pull/746#discussion_r570879556).
Funnily enough, we may want to make a lint for lint suppressions 😂 — not sure if ESLint can already be configured to have a kind of "strict mode" like this, or we'd have to cook something up ourselves. 🤔
cc @kresimir-coko
=> docs(guidelines): provide more info about narrowing suppression scope

third-party/projects/jquery-form/package.json
Our first release is going to be `@liferay/jquery-form` v3.51.0-liferay.1, and is going to correspond to the same code as upstream, but with the patch originally proposed in https://github.com/liferay-frontend/liferay-portal/pull/699 applied to it. I'll send a separate PR for that in a minute. Subsequent releases, if any, will be `@liferay/jquery-form` v3.51.0-liferay.2, v3.51.0-liferay.3 etc. ie. the same versioning scheme we employ in [liferay-ckeditor](https://github.com/liferay/liferay-ckeditor) — the idea is that you can see at a glance what upstream version we're using as a base, and on top of that you can tell how many patches/tweaks we've applied on top.
=> chore(jquery-form): prepare to release jquery-form under named scope

third-party/projects/jquery-form/jquery.form.js
Applies the suggested fix that is sitting in [an unmerged PR on the upstream repo](https://github.com/jquery-form/form/pull/586) and which we previously tried shipping [via direct patch](https://github.com/liferay-frontend/liferay-portal/pull/699).
Needed for: https://github.com/liferay/liferay-frontend-projects/issues/394
=> fix(jquery-form): avoid XSS

.gitignore, CONTRIBUTING.md, third-party/README.md, third-party/projects/jquery-form/CONTRIBUTING.md, third-party/projects/jquery-form/jquery.form.js
Just some minor follow-ups in light of the first release:
- Fixed a complaint that jshint had.
- Ignore build cruft.
- Add notes on steps taken to release.
=> chore(jquery-form): post-release cleanup

projects/npm-tools/packages/npm-scripts/src/jsp/lintJSP.js, projects/npm-tools/packages/npm-scripts/test/jsp/lintJSP.js
On `master` we don't need to support IE any more, which means that we can use arrow functions in JSP now (we could previously use them in JS because we transpile pretty much all JS).
Once [this PR](https://github.com/liferay-frontend/liferay-portal/pull/793) goes in, our Java-powered SF tooling won't complain about arrow functions any more. So, we can go one step further (this commit) and actually enforce the preference for arrow functions in callback positions in JSP. We already do this for JS files.
This is a "breaking" change because it will trigger [over a 1,000 lint errors in `master`](https://gist.github.com/wincent/7f385dfb04e4d97cd5246fcf9eb71414).
The good news is there is an autofix that produces [this pretty sane-looking 11.7k-line …
=> feat(npm-scripts)!: prefer arrow callbacks in JSP too

projects/npm-tools/packages/npm-scripts/package.json
Bumps us from 21.2.1 to 21.3.0. [Release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/eslint-config%2Fv21.3.0).
Main things of interest in there are:
-   Adding Cavannaugh to the list of possible deprecations: [#389](https://github.com/liferay/liferay-frontend-projects/pull/389)
-   Bug fix to handle the edge case of "strange" imports of the form `import '.'`: [#137](https://github.com/liferay/liferay-frontend-projects/pull/137)
Seeing as I am about to cut a release of `@liferay/npm-scripts`, may as well flush these pending changes out.
=> chore(npm-scripts): update to latest @liferay/eslint-config

maintenance/projects/js-toolkit/packages/babel-plugin-namespace-modules/src/index.js, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/__tests__/namespace.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/namespace.ts, projects/npm-tools/packages/npm-bundler-preset-liferay-dev/config.json, projects/npm-tools/packages/npm-scripts/src/utils/SignalHandler.js, projects/npm-tools/packages/npm-scripts/src/utils/bundlerNamespace.js, projects/npm-tools/packages/npm-scripts/src/utils/createBridges.js, projects/npm-tools/packages/npm-scripts/src/utils/createFederationConfig.js, projects/npm-tools/packages/npm-scripts/src/utils/createTempFile.js, projects/npm-tools/packages/npm-scripts/src/utils/getNamespacedVersionedPackageName.js
This is needed as a prerequisite for https://issues.liferay.com/browse/LPS-127990
I've tested it locally and build is OK. Runtime doesn't fail but we'll see in the CI if we need anything else. :crossed_fingers: 
----
Server side PR here :point_right: https://github.com/liferay-frontend/liferay-portal/pull/813
=> feat: support scoped npm packages

guidelines/general/options.md
I admit this guidance is a bit weakly worded because it says "you should (blah)" but it also lists "an acceptable alternative approach", because we have multiple examples of the latter already in liferay-portal, and there is no real urgency to change them (the pattern is fine).
Closes: https://github.com/liferay/liferay-frontend-projects/issues/409
=> docs(guidelines): add guidance on options objects

package.json, yarn.lock
This came in via 18e9c76f12 but I don't think we actually need this as a top-level `devDependency`. It will come in anyway transitively with liferay-frontend-theme-styled and liferay-frontend-theme-unstyled, which were added in f5da76606f.
Originally looked at this because of [this dependabot PR](https://github.com/liferay/liferay-frontend-projects/pull/414).
I don't think this will stop the bot from reminding us to update our own internal dependencies (that we aren't even directly using here anyway), so I might also tell the bot to ignore this dependency.
=> refactor: remove explicit dependency on clayui/css

projects/npm-tools/packages/npm-scripts/src/utils/getJestModuleNameMapper.js
Needed to fix CI errors in https://github.com/liferay-frontend/liferay-portal/pull/813
=> fix(npm-scripts): support scoped package names in jest

projects/npm-tools/packages/npm-scripts/package.json
Now that we have 10.3.0, we need to update that here.
Once this is merged and a new version is released, we should be able to use the `dartSass` option for building themes
=> feat(npm-scripts): bump liferay-theme-tasks dependency to 10.3.0

guidelines/dxp/code_review.md
As [requested here](https://github.com/liferay-frontend/liferay-portal/pull/821#issuecomment-785739058).
Adding Jon Mak, in order to bring balance to The Force.
=> docs(guidelines): update frequent reviewers list

projects/npm-tools/packages/npm-scripts/package.json, projects/npm-tools/packages/npm-scripts/src/config/babel.json, projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/test/utils/getMergedConfig.js, yarn.lock
So I need to add some code to liferay-portal in service of [LPS-127081](https://issues.liferay.com/browse/LPS-127081) ("Implement and integrate Global JS Store mechanism in DXP") and I think it would be very useful to "future proof" it by making sure it is TypeScript-ready. We probably don't want to have our store just be un untyped "bag of data", especially if we are going to have to live with and support this API for many years and it is going to become a central channel for cross-app communication with DXP. Example libraries which share this point of view are [Undux](https://github.com/bcherny/undux) and [Recoil](https://recoiljs.org), but they are both React-specific and we want something generic.
So, we can either:
1. Build and ship the API in TypeScript in a way that lends itself to …
=> feat(npm-scripts): add some basic support for building with TypeScript

.eslintrc.js, maintenance/projects/js-toolkit/.eslintrc.js, projects/eslint-config/index.js, projects/eslint-config/plugins/liferay/lib/rules/padded-test-blocks.js, projects/eslint-config/plugins/portal/lib/rules/no-react-dom-render.js, projects/js-toolkit/.eslintrc.js
Now that we no longer support IE on the DXP master branch, we can turn this rule off by default, and then opt explicitly back into it on the maintenance branches (eg. 7.3.x and older), or in products which go to the maintenance branches (eg. alloy-editor etc).
The truth is that even in places where we need to support IE, this rule was always very conservative; we polyfill/transpile in IE, and [the only reason that that couldn't be relied upon to work swimmingly](https://github.com/liferay/liferay-frontend-projects/issues/354) is that Babel used `Symbol.iterator` in its output and we weren't 100% confident in our polyfill coverage.
In any case, I'll be following up with some pulls to other projects/branches to make turn the rule back on where it is still needed.
One final note: I am …
=> feat(eslint-config)!: turn off no-for-of-loops rule by default

projects/eslint-config/plugins/liferay/docs/rules/no-duplicate-imports.md, projects/eslint-config/plugins/liferay/lib/rules/no-duplicate-imports.js, projects/eslint-config/plugins/liferay/tests/lib/rules/no-duplicate-imports.js
It's legit to import from the same module twice, as long as exactly one of the imports is a type-only import:
```ts
import Thing from './Thing';
import type {ThingT} from './Thing';
```
In the old days, Flow had this syntax and TypeScript didn't. You would instead have to import the type as though it were a value like this, and trust the TypeScript compiler to figure out that you only wanted it for the type definition:
```ts
import Thing, {ThingT} from './Thing';
```
This made it tricky to do things like circular type-only imports (ie. modules A and B wanting to share type definitions with each other). But TypeScript has support for this now and [the way we're currently using this it in liferay-portal](https://github.com/liferay-frontend/liferay-portal/pull/874), we don't even have a …
=> feat(eslint-config): teach no-duplicate-imports rule about type imports

projects/eslint-config/plugins/liferay/tests/lib/rules/imports-first.js, projects/eslint-config/plugins/liferay/tests/lib/rules/no-absolute-import.js, projects/eslint-config/plugins/liferay/tests/lib/rules/sort-import-destructures.js, projects/eslint-config/plugins/liferay/tests/lib/rules/sort-imports.js
These are just additions to the test suite to show that these import-related rules already support TypeScript without breaking.
Other pulls pushed so far are:
- https://github.com/liferay/liferay-frontend-projects/pull/431 ("teach no-duplicate-imports rule about type imports")
- https://github.com/liferay/liferay-frontend-projects/pull/433 ("teach import-extensions rule about .ts, .tsx")
Both of those required actual changes to the code, unlike this one.
Only remaining one after this will be the `group-imports` rule, but that one is complex enough to warrant its own changelog entry and therefore go in via a separate PR.
=> test(eslint-config): show that various rules already support TS

projects/eslint-config/plugins/liferay/lib/rules/import-extensions.js, projects/eslint-config/plugins/liferay/tests/lib/rules/import-extensions.js
This is a companion to [#431](https://github.com/liferay/liferay-frontend-projects/pull/431) (which teaches the no-duplicate-imports rule about type-only imports). I'm going through all the other import-related rules and making sure they do the right thing with TypeScript.
So, in this commit, we add tests to show that both type-only and value-only imports/exports from ".ts" and ".tsx" files work with this rule, which requires us to add those extensions to the list of "banned" extensions.
Technically, a "breaking" change because we'll be potentially catching more lint error than we were before.
=> feat(eslint-config)!: teach import-extensions rule about .ts, .tsx

projects/eslint-config/jest.config.js, projects/eslint-config/plugins/liferay/docs/rules/group-imports.md, projects/eslint-config/plugins/liferay/docs/rules/sort-imports.md, projects/eslint-config/plugins/liferay/lib/common/imports.js, projects/eslint-config/plugins/liferay/lib/rules/group-imports.js, projects/eslint-config/plugins/liferay/lib/rules/no-duplicate-imports.js, projects/eslint-config/plugins/liferay/lib/rules/sort-imports.js, projects/eslint-config/plugins/liferay/tests/lib/rules/group-imports.js, projects/eslint-config/plugins/liferay/tests/lib/rules/sort-imports.js, projects/eslint-config/test/integration.js
Via [Slack thread](https://liferay.slack.com/archives/C3JBR21HA/p1615278868119400).
We discussed two possible end states:
1.  Mix type-only imports among other imports:
import X from './X';
import type {T} from './X';
import Z from './Z';
2.  Put type-only imports at the end, in a section of their own:
import X from './X';
import Z from './Z';
import type {T} from './X';
We agreed that, while "1" is easier to implement, we like the conceptual separation of "2". Type-only inputs really are totally different beasts (for example, they get elided during compilation, for example).
Changing the group-imports rule alone doesn't produce the desired effect; it merely makes sure that type-only imports start a new group. eg.
```ts
import a from 'a';
import b from 'b';
import type {T} from 'a'; …
```
=> feat(eslint-config)!: teach sort-imports, group-imports to separate type-only inputs

projects/eslint-config/plugins/liferay/docs/rules/no-duplicate-class-names.md, projects/eslint-config/plugins/liferay/docs/rules/sort-class-names.md, projects/eslint-config/plugins/liferay/docs/rules/trim-class-names.md, projects/eslint-config/plugins/liferay/lib/common/className.js, projects/eslint-config/plugins/liferay/tests/lib/rules/no-duplicate-class-names.js, projects/eslint-config/plugins/liferay/tests/lib/rules/sort-class-names.js, projects/eslint-config/plugins/liferay/tests/lib/rules/trim-class-names.js, projects/eslint-config/test/integration.js
Extends our three existing `class-names` rules:
- `no-duplicate-class-names`
- `sort-class-names`
- `trim-class-names`
to handle `"customClassName"` attributes with string keys as well, like these:
```jsx
<CustomPopover triggerClassName="   foo foo bar  " />
```
Which would be fixed to:
```jsx
<CustomPopover triggerClassName="bar foo" />
```
Closes: https://github.com/liferay/liferay-frontend-projects/issues/417
=> feat(eslint-config)!: teach class-names rules about "customClassName" attributes

package.json, projects/npm-tools/packages/npm-scripts/package.json, yarn.lock
This updates both the version that we use internally in the monorepo and also the dependency that npm-scripts carries with it into liferay-portal.
This combo (latest `@liferay/eslint-config` + latest `eslint`) is working well [over in good old alloy-editor](https://github.com/liferay/alloy-editor/pull/1469), so I think it's safe to roll out everywhere.
=> chore: update ESLint version from 7.10.0 to 7.21.0

projects/npm-tools/packages/npm-scripts/src/webpack/writeWebpackFederationEntryPoint.js
This is the npm-scripts side fix of https://issues.liferay.com/browse/LPS-128988
It has been manually tested by @zhangyan0701 in a Windows box.
=> fix(npm-scripts): use correct paths for Windows

projects/js-toolkit/packages/js-toolkit-core/src/node/__tests__/namespace.test.ts, projects/js-toolkit/packages/js-toolkit-core/src/node/namespace.ts
This is needed for https://issues.liferay.com/browse/LPS-129200 so that we can use bundler 3 to build `frontend-js-recharts-web` when undoing the webpack federation build.
Tested locally with `liferay-portal` but also added some unit tests to be safer.
=> fix(js-toolkit): support namespaces originated from scoped packages

package.json, projects/js-toolkit/packages/generator-js/package.json, projects/js-toolkit/packages/js-toolkit-scripts/package.json, projects/js-toolkit/packages/npm-bundler/package.json, projects/npm-tools/packages/npm-scripts/package.json, yarn.lock
Just an increase in js-toolkit-core version number to be able to release a new npm-bundler
=> fix(js-toolkit): use new js-toolkit-core version to fix scoped namespaces

maintenance/projects/js-toolkit/packages/liferay-npm-bundler-plugin-exclude-imports/src/__tests__/index.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler-plugin-exclude-imports/src/index.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler-plugin-inject-imports-dependencies/src/index.js
This is needed since we allowed to inherit the base configuration from the liferay-portal project in
npm-scripts.
This is because now we don't have a way to disable the inherited imports other than setting them
to false one by one. But that makes it very difficult to configure projects, because if we add a new
import to the base config, we need to check all other projects one by one.
With this change, we can use the same base config in all projects without making the build fail
because a project excludes itself from the JAR because the bundler thought it was imported
(rather than the project being built).
Example: the [current base npm-scripts config](https://github.com/liferay/liferay-portal/blob/8cf1bfb038cd72870018de6b9f37c082b71e4519/modules/npmscripts.config.js#L32) in portal imports …
=> fix: don't treat ourselves as a valid import

projects/eslint-config/plugins/portal/lib/rules/no-metal-plugins.js, projects/eslint-config/plugins/portal/tests/lib/rules/no-metal-plugins.js
Fixes https://github.com/liferay/liferay-frontend-projects/issues/386
Hey crew, first time doing something like this so please let me know if I missed something or done something wrong, but here's what I've done.
- added `affix`, `position`, and `throttle` and others to the list of deprecated modules. There are leftover modules but they're still used
- fixed the warning text of `keyboard-focus`. I couldn't find our own implementation, other than `useKeyboardNavigation` but that one didn't look the same, so just referenced a default focus behaviour
- added tests for the new deprecated modules
- It wasn't clear to me if I'm supposed to go to do what @wincent mentioned in https://github.com/liferay/liferay-frontend-projects/issues/386#issuecomment-766996855 - the 7.2 and 7.3 config update
- …
=> feat(eslint-config)!: add several packages to the no-metal-plugin eslint rule

yarn.lock
[CI is failing](https://github.com/liferay/liferay-frontend-projects/runs/2140506487) on master (cfb2c217c449f717e473) right now because we just prepared the v23.0.0 release of `@liferay/eslint-config`, but `@liferay/npm-scripts` still depends on v22.0.0.
Now, @kresimir-coko will fix that tomorrow when he completes the release and updates the dependency, so for now I am just freshening the lockfile to keep CI green. (I could also fix this by updating the dependency myself, but that would require me to finish the release, and I don't want to do that.)
=> chore(monorepo): temporarily fix lockfile failure in CI

guidelines/general/security/two_factor_authentication.md
I'll be hounding people in Slack over this shortly, so I want to have a thing I can link to.
=> docs(guidelines): add strong recommendation to use 2FA

.github/workflows/global.yml, projects/npm-tools/packages/js-publish/src/index.js
This comes from [the thread in Slack today](https://liferay.slack.com/archives/C3JBR21HA/p1616068068087200) where we saw that the meaning of "OTP" in the context of npm may not be clear to everybody.
So, instead of just asking for an OTP token, include a shortlink to [this page](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/security/two_factor_authentication.md) that explains it in more detail.
In case you're wondering about whether git.io is a sketchy third-party service that could disappear or start redirecting to hostile sites any day now, don't worry; it's [an official GitHub service](https://github.blog/2011-11-10-git-io-github-url-shortener/).
As a bonus, if you are so audacious as to proceed without supplying an OTP, we now scold you as seen …
=> feat(js-publish): educate people about 2FA

projects/npm-tools/packages/npm-scripts/package.json, yarn.lock
Not sure if I needed to push the generated `yarn.lock` file, so I opted not to.
This is a fix that @wincent mentioned in https://github.com/liferay/liferay-frontend-projects/pull/460
=> chore(npm-scripts): bump @liferay/eslint-config version from v22.0 to v23.0

projects/npm-tools/packages/npm-scripts/src/utils/getJestModuleNameMapper.js
As noted [here](https://github.com/liferay-frontend/liferay-portal/pull/925) we are adding TS to modules in DXP, but we will continue to use names like "index.js" in our "main" fields in our "package.json" files (this is because our bundler/loader/registry use "main" and expect it to point to an ES5-ish file that is ready to serve to the browser). That is, in a module that has an "index.ts" file in the "src/" folder, we will still say "index.js" in the "main" field, because that is the name of the built-module that we can expect to exist at runtime.
Doing a quick survey of "main" fields in DXP you can see that the most common names are things like "index.js" and "index.es.js", but we also have "index.es" in some places. In other words, the extension is optional, but we do expect the file …
=> feat(npm-scripts): teach getJestModuleNameMapper about TS manifests

maintenance/projects/js-toolkit/packages/babel-plugin-alias-modules/src/index.ts, projects/eslint-config/index.js
As seen in PRs such as:
- https://github.com/liferay-frontend/liferay-portal/pull/925
- https://github.com/liferay-frontend/liferay-portal/pull/942
We need to tweak the ESLint rules in order to accommodate our growing TypeScript usage. Without this, some common idiomatic patterns create false positives.
Without this, even a simple
import React from 'react';
will lead to:
17:8  error  'React' was used before it was defined.  no-use-before-define
Note that we're allowing functions to be used before they are defined because:
1.  Function hoisting is an oft-exploited idiomatic feature of JS.
2.  Liferay likes keeping things in alphabetical, not topological, order.
Technically a breaking change because this will lead to new lint errors popping up if/when this is backported to much older …
=> feat(eslint-config)!: adapt no-use-before-define set-up for TypeScript

projects/npm-tools/packages/npm-scripts/package.json, yarn.lock
This allows us to use TS in React components, as seen in PRs like:
- https://github.com/liferay-frontend/liferay-portal/pull/925
- https://github.com/liferay-frontend/liferay-portal/pull/942
Note that `npm-scripts` may not be the definitive home for this; it's just one of the two places that we can put it:
1.  Inside `frontend-js-react-web`, because that's where our `react` dependency comes from, and it makes sense to version the React package and its type definitions together (better still would be if the React team shipped TypeScript types with the package).
2.  Inside `npm-scripts` because that is "The Blessed" way of getting devDependencies into liferay-portal; in fact, the only reason we get away with it in `frontend-js-react-web` is due to [a "temporary …
=> feat(npm-scripts): add @types/react-dom dependency

projects/npm-tools/packages/npm-scripts/src/config/jest.config.js
In PRs like:
- https://github.com/liferay-frontend/liferay-portal/pull/925
- https://github.com/liferay-frontend/liferay-portal/pull/942
We have had to explicitly adjust the `testMatch` directive to catch TS files. We may as well do this automatically throughout liferay-portal.
Seeing as I was changing this, note that I made the pattern a little stricter (adding `<rootDir>`) because this brings us into more exact alignment with our conventions (which clearly state that source should go in `src/` and tests should go in `test/`).
**Note:** When we integrate this with liferay-portal, we not only have to clean out the `jest.config.js` that exists in those two PRs, but also the `jest` field in the `package.json` of `remote-app-client-js`, which is mentioned below.
**Test plan:**
1. Run `yarn …
=> feat(npm-scripts): automatically run TS tests

package.json, projects/npm-tools/packages/npm-scripts/package.json, yarn.lock
Seeing as we're sending TS stuff to liferay-portal, may as well take the opportunity to freshen things up.
**Test plan:** `yarn add -W --dev path/to/npm-scripts` in `modules/` and confirm that all TS modules still building and testing (ie. `remote-app-client-js`, `frontend-js-state-web`, and with https://github.com/liferay-frontend/liferay-portal/pull/942 checked out, `frontend-js-react-web`).
=> chore(npm-scripts): update to typescript@4.2.3

.prettierignore, projects/npm-tools/packages/npm-scripts/.gitignore, projects/npm-tools/packages/npm-scripts/README.md, projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/apps/frontend-js/frontend-js-clay-sample-web/package.json, projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/apps/frontend-js/frontend-js-react-web/package.json, projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/apps/frontend-js/frontend-js-state-web/package.json, projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/apps/remote-app/remote-app-client-js/package.json, projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/yarn.lock, projects/npm-tools/packages/npm-scripts/jest.config.js, projects/npm-tools/packages/npm-scripts/src/config/tsconfig-base.json, projects/npm-tools/packages/npm-scripts/src/index.js, projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/src/scripts/check/preflight.js, projects/npm-tools/packages/npm-scripts/src/scripts/lint.js, projects/npm-tools/packages/npm-scripts/src/scripts/types.js, projects/npm-tools/packages/npm-scripts/src/typescript/README.md, projects/npm-tools/packages/npm-scripts/src/typescript/configureTypeScript.js, projects/npm-tools/packages/npm-scripts/src/typescript/getTypeScriptBuildOrder.js, projects/npm-tools/packages/npm-scripts/src/typescript/getTypeScriptDependencyGraph.js, projects/npm-tools/packages/npm-scripts/src/typescript/runTSC.js, projects/npm-tools/packages/npm-scripts/src/utils/color.js, projects/npm-tools/packages/npm-scripts/src/utils/getJestModuleNameMapper.js, projects/npm-tools/packages/npm-scripts/src/utils/getWorkspaces.js, projects/npm-tools/packages/npm-scripts/src/utils/stringify.js, projects/npm-tools/packages/npm-scripts/test/sass/build.js, projects/npm-tools/packages/npm-scripts/test/typescript/configureTypeScript.js, projects/npm-tools/packages/npm-scripts/test/typescript/getTypeScriptBuildOrder.js, projects/npm-tools/packages/npm-scripts/test/utils/stringify.js
~This is still a WIP so parking it here as a draft.~
~So tomorrow I'm going to look at that last one. The pieces I've already added to this PR should make it fairly straightforward: we have a function that returns us info about the dependency graph between TypeScript projects, including their name, their location on disk, what their `main` field points at etc, so we can use that to fill out the required `paths` and `references` section in the `tsconfig.json`.~
~My testing indicates that we can add extra fields to that file without `tsc` complaining, so we'll leverage that to put in some `__generated__` property and an optional `__overrides__` one which can be used in those expected rare cases (like `remote-app-client-js`) where the vanilla config won't work. So far, I think that all the …
=> feat(npm-scripts): manage TS type artifacts

projects/npm-tools/packages/npm-scripts/src/scripts/format.js, projects/npm-tools/packages/npm-scripts/src/scripts/lint.js, projects/npm-tools/packages/npm-scripts/src/utils/inCurrentWorkingDirectory.js, projects/npm-tools/packages/npm-scripts/test/scripts/format.js
As noted in the doc comment, Yarn (when we do `yarn run liferay-npm-scripts`) will `cd` to the closest project root (ie. directory that has a `package.json` file) before invoking our tool. By that time, it is "too late", to know where we were invoked from. Fortunately, it sets an `INIT_CWD` environment variable with this information.
Whenever we run the `lint()` or `format()` functions (whether in `check` or `fix` modes), we check to see if `INIT_CWD` is defined and different from our apparent "current" working directory. If there is a discrepancy, that means that the user is probably working down inside a `src/` directory (or similar), or they are running in a project that doesn't have a `package.json` (eg. `click-to-chat-web`). Nevertheless, projects like `click-to-chat-web` do have JSP …
=> feat(npm-scripts): allow format/lint to run without package.json

projects/npm-tools/packages/npm-scripts/src/utils/inCurrentWorkingDirectory.js
This is a fix on top of [#484](https://github.com/liferay/liferay-frontend-projects/pull/484).
I wrote that one from the Linux box, and tests were green there (as they were on Linux and Windows in the CI environment), but on running them on macOS today I see failures caused by the fact that macOS uses symlinks in the directory hierarchy used for temporary files. This means that we can "see" a path like:
/private/var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/format-1HaaBt
from `process.cwd()`, but get a different version of that via the `INIT_CWD` environment variable:
/var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/format-1HaaBt
But note, they are the same directory. This breaks our equality check in the tests on macOS and has us `cd`-ing up all the way to `/`. Whoops.
So, even though …
=> fix(npm-scripts): deal with symlinks in `inCurrentWorkingDirectory()`

projects/npm-tools/packages/npm-scripts/src/index.js, projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/src/scripts/check.js, projects/npm-tools/packages/npm-scripts/src/scripts/check/preflight.js, projects/npm-tools/packages/npm-scripts/src/scripts/fix.js, projects/npm-tools/packages/npm-scripts/src/scripts/types.js, projects/npm-tools/packages/npm-scripts/src/typescript/configureTypeScript.js, projects/npm-tools/packages/npm-scripts/src/typescript/runTSC.js, projects/npm-tools/packages/npm-scripts/test/typescript/configureTypeScript.js
As [requested here](https://github.com/brianchandotcom/liferay-portal/pull/100574#issuecomment-814446826).
Note that this still isn't going to be the most beautiful code ever, but here is the change:
- [Before gist](https://gist.github.com/wincent/9a55b26389b9e1e15ec802f7feef0b13)
- [After gist](https://gist.github.com/wincent/3ff31e80550cc00d3df39a03659ed0b0)
Note that `tsc` tends to run things together, avoiding totally empty lines, so the style is quite cramped. We don't have any lints that force stuff to be spaced out (ie. even if I were to run ESLint over the files in addition to Prettier), so this is about as good as it gets. Note that at least the docblock comments have an empty line above them, so that's something. Also note that we hackily insert an extra line after the license …
=> feat(npm-scripts): format generated `.d.ts` files

projects/npm-tools/packages/npm-scripts/test/scripts/lint.js
Today we have a new problem caused by 77db6f875cdb, and this time the fix we applied in 7cabd4f8efa9 doesn't cover it.
Our prior fix dealt with cases where a directory like "/var" might actually be a symlink to "/private/var", meaning that you can't detect the "identity" of a directory using `===` without first resolving symlinks. Probably never happens in actual use, but could (and did) happen in the test suite. So, we added code to resolve symlinks before comparing.
Well, today we have another case of something that only happens in the test suite (which is why I am labeling this with the "test" scope instead of the "fix" scope, even though it is a bug).
In the lint tests, we `cd` down into our `modules` directory under `__fixtures__` folder and try to run lints. Now, `INIT_CWD` will be …
=> test(npm-scripts): avoid unhandled promise rejection in tests

guidelines/dxp/react_state_management.md
This comes out of [liferay-frontend#874](https://github.com/liferay-frontend/liferay-portal/pull/874).
As discussed there, we want to make sure that people know how/when to use the new global state API, and a huge prerequisite for that is knowing when _not_ to use it, which in turn means knowing how to get the most out of React's built-in state management abstractions, which will continue to cover probably 95% of use cases.
=> docs(guidelines): add recommendations on state management for React

guidelines/dxp/code_review.md, guidelines/dxp/debugging.md
Just noticed will preparing [another PR](https://github.com/liferay/liferay-frontend-projects/pull/493) that these image links are broken (and would have been broken since these docs got migrated into the monorepo).
=> docs(guidelines): fix broken image links

projects/npm-tools/packages/npm-scripts/src/typescript/runTSC.js
Noticed while preparing [this PR](https://github.com/liferay-frontend/liferay-portal/pull/970) yesterday that if you try to start porting a module to TypeScript by doing this:
```sh
touch tsconfig.json
yarn run build
```
that it will die with:
ENOENT: no such file or directory, scandir './types'
This happens because you haven't created any `.ts` files yet, and so `tsc` never creates the `types` directory. That in turn means that when we try to post-process everything matching `**/*.d.ts` in `types/` glob expansion is going to complain that there _is_ no `types/` directory.
**Test plan:**
touch tsconfig.json
yarn run build # see ENOENT
touch tsconfig.json
yarn run build # see tsconfig.json get filled out; no error
=> fix(npm-scripts): don't post-process TypeScript if there is no TS

README.md
This was originally going to be [like this](https://gist.github.com/wincent/801e9f3695a41018c4951a0b4b8f65f0) but due to merge conflicts I dropped the `README.md` changes, leaving only 3e9fae69736a1d00b757d8bc81b7.
Now that the dust has settled, looping back and re-doing it in the new format.
Right now we have a "Projects" section that already includes some links to stuff under `maintenance/`, so this new "Maintenance" section stands out a bit. But I know @izaera wants to keep evolving this, so I'll leave it up to him to think about new ways of categorizing stuff.
As noted in [this Slack thread](https://liferay.slack.com/archives/C3JBR21HA/p1618585240124300?thread_ts=1618573703.116200&cid=C3JBR21HA) we haven't explicitly explained what `maintenance/` is for, apart from in commit messages …
=> docs(monorepo): update top-level README to include Senna links

projects/eslint-config/plugins/liferay/lib/common/imports.js, projects/eslint-config/test/integration.js
Stops spurious complaints about `imports must be grouped (unexpected blank line before: "frontend-js-web")` given code as seen in the included regression test.
Closes: https://github.com/liferay/liferay-frontend-projects/issues/515
=> fix(eslint-config): fix group-imports edge case

maintenance/projects/js-themes-toolkit-v9-x/packages/generator-liferay-theme/lib/util.js, projects/js-themes-toolkit/packages/generator-liferay-theme/lib/util.js
This PR shows a message when the generator is run showing a link to the [themes versions table](https://github.com/liferay/clay/wiki/Liferay-Portal-@clayui-css-Versions) inside Clay.
Something like this:
```sh
my-project $ yo liferay-theme
Welcome to the splendid Themes SDK generator!
ℹ️ This version of the Themes SDK (10.0.2) supports Liferay DXP
and Portal CE from 7.2 to 7.3.
For older versions, please use v8 of the toolkit:
> npm install -g generator-liferay-theme@^8.0.0 ↩
> yo liferay-theme:app ↩
ℹ️ For detailed information on version numbers of unstyled, styled,
classic, admin, frontend-css-common, @clayui/css and Bootstrap
used by each release of Liferay DXP and Portal CE see the table at:
https://github.com/liferay/clay/wiki/Liferay-Portal-@clayui-css-Versions
? What would you like …
```
=> feat: show documentation on what to expect about dependency version numbers

maintenance/projects/js-toolkit/packages/liferay-npm-build-support/src/resources/start/index.js.ejs
Recently created an Angular Widget using `yo liferay-js` and tried to run `npm run start` and got the following error:
I moved the declaration of the mocked Liferay object before requiring the main module. I also added the mock for `Liferay.ThemeDisplay.getPathContext` which is used by the Angular components to declare the `templateUrl` property:
```
@Component({
templateUrl: 
Liferay.ThemeDisplay.getPathContext() + 
'/o/angular-sample/app/app.component.html'
})
export class AppComponent {
...
```
=> fix(js-toolkit): declare Liferay mock before requiring main module when running 'npm run start'

projects/js-themes-toolkit/CONTRIBUTING.md
We have found that the process may fail without this step.
=> docs(js-themes-toolkit): add a new step to local themes toolkit test procedure

maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/scoped/.npmbundlerrc, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/scoped/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/index.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/jar.ts
Tested locally with a scoped project.
Closes #446
=> fix(js-toolkit): support scoped packages when building JAR files

maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-autopreset/node_modules/autopreset/config.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-autopreset/node_modules/autopreset/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-autopreset/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-ignored-autopreset/.npmbundlerrc, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-ignored-autopreset/node_modules/autopreset/config.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-ignored-autopreset/node_modules/autopreset/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-ignored-autopreset/node_modules/preset/config.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-ignored-autopreset/node_modules/preset/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-ignored-autopreset/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-two-autopresets/node_modules/autopreset/config.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-two-autopresets/node_modules/autopreset/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-two-autopresets/node_modules/autopreset2/config.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-two-autopresets/node_modules/autopreset2/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/__fixtures__/project/with-two-autopresets/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/__tests__/index.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project/index.ts
This implements https://github.com/liferay/liferay-frontend-projects/issues/542
I've tested it locally using a local npm registry for the preset and yarn-linking the bundler in a local copy of [the PoC project](https://github.com/izaera/fat-jar-sample/tree/886597222590a965ab1b641d91cc1bd41d8f2f44) and it works as expected.
In addition I've provided some unit tests to avoid breaking it in the future.
=> feat(js-toolkit): support for autopresets

guidelines/dxp/how_to_use_css_custom_properties.md
In this PR:
- Added the warning "not supported in IE11"
- Added the warning "don't use it in production"
- Added "how to use it in custom theme"
- Added StyleBook references
- Updated supported components variables list
- Simplified examples
=> docs(guidelines): add missing info in css-custom-properties

maintenance/projects/js-toolkit/packages/babel-preset-liferay-standard/package.json, maintenance/projects/js-toolkit/packages/babel-preset-liferay-standard/src/index.js, maintenance/projects/js-toolkit/yarn.lock
Fixes #565
Tested locally with the same project I used to reproduce it (an empty shared bundle with just `recoil` dependency)
=> fix(js-toolkit): support spread operator when bundling modules

projects/npm-tools/packages/changelog-generator/src/index.js
Found when trying to make a release of JS Toolkit v2.
----
When the version field is not present in package.json and --interactive is
used the tools fails without a meaningful error message.
This fix makes it show a proper message.
=> fix(changelog-generator): don't fail when no version is present

projects/eslint-config/plugins/portal/index.js, projects/eslint-config/plugins/portal/lib/rules/no-react-dom-create-portal.js, projects/eslint-config/plugins/portal/tests/lib/rules/no-react-dom-create-portal.js
Fixes https://github.com/liferay/liferay-frontend-projects/issues/553
Aim of this is to aim people towards using our component in DXP. 
This feature shouldn't be added to DXP until https://github.com/liferay-frontend/liferay-portal/pull/1091 is merged
=> feat(@liferay/eslint-config): add rule to prevent developers from using createPortal directly from react-dom.

projects/eslint-config/plugins/liferay/lib/rules/no-abbreviations.js, projects/eslint-config/plugins/liferay/tests/lib/rules/no-abbreviations.js
Caught this issue while trying to get this merged to portal
=> fix(eslint-config): add case for abbreviation being a key on an object

package.json, projects/js-themes-toolkit/packages/liferay-theme-tasks/package.json, yarn.lock
Updates dependency version and moves the dependency to where the package is used. 
context: https://github.com/liferay/liferay-frontend-projects/pull/612
=> chore: move devDependency to the project it is used in

projects/eslint-config/index.js, projects/eslint-config/plugins/liferay/index.js, projects/eslint-config/plugins/liferay/lib/rules/empty-line-between-elements.js, projects/eslint-config/plugins/liferay/tests/lib/rules/empty-line-between-elements.js, projects/eslint-config/test/integration.js
With ASTExplorer finally working, I had the chance to make this rule actually work... kinda.
For code like this, it throws out an error, as it's supposed to, on lines where the `div` and `small` are opening:
```js
<label className="form-group-autofit">
<span className="form-group-item">
{label}
{subTitle && (
<span className="font-weight-normal form-text">
{subTitle}
</span>
)}
</span>
<div className="flex-row form-group-item">
<ClaySlider
className="w-100"
max={max}
min={min}
onValueChange={onValueChange}
showTooltip={false}
value={value}
/>
<small className="font-weight-normal form-text ml-3">
{value + '%'}
</small>
</div>
</label>
```
Now, the problem I encountered was the indentation when adding a new line inside the `fix: (fixer) => ...`. I tried to add the amount of tabs equalling …
=> feat(eslint-config): add an ESlint rule that adds an empty line between sibling elements

projects/npm-tools/packages/npm-scripts/package.json
Update the `eslint-config` version used by `npm-scripts` to `27.0.0.` as it's been bumped because I merged the `empty-line-between-elements` rule.
=> feat(npm-scripts): update eslint-config version

projects/npm-tools/packages/js-publish/src/index.js
fixes https://github.com/liferay/liferay-frontend-projects/issues/639
This is to help developers know what to do next when publishing fails. This will help us avoid people running `yarn version` multiple times and accidentally pushing non-published versions to upstream.
=> fix(js-publish): add message when publishing fails

projects/eslint-config/README.md, projects/eslint-config/index.js, projects/eslint-config/plugins/liferay/docs/rules/no-length-jsx-expression.md, projects/eslint-config/plugins/liferay/index.js, projects/eslint-config/plugins/liferay/lib/rules/no-length-jsx-expression.js, projects/eslint-config/plugins/liferay/tests/lib/rules/no-length-jsx-expression.js
fixes #648
This doesn't address if a user creates a variable first, but we can add that later if needed
=> feat(eslint-config): add rule to ensure JSX expressions guard against rendering 0 on accident

projects/js-toolkit/packages/js-toolkit-core/package.json
We were missing `ejs` dependency.
=> fix(js-toolkit-core): add missing dependency

projects/eslint-plugin/README.md
This is a proper iteration of https://github.com/liferay/liferay-frontend-projects/pull/685, as that one was a quick Github UI PR, that obviously sucks.
=> docs(eslint-plugin): Fix bleeding code block in README

maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/lib/r2/liferay-r2/css-parse.js, maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/lib/r2/liferay-r2/index.js, maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/lib/r2/liferay-r2/plugins/bg.js, maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/lib/r2/liferay-r2/plugins/fontawesome.js, maintenance/projects/js-themes-toolkit-v9-x/packages/liferay-theme-tasks/lib/r2/liferay-r2/plugins/yui3.js, maintenance/projects/js-themes-toolkit-v9-x/scripts/qa.js, maintenance/projects/js-toolkit/packages/babel-plugin-add-module-metadata/src/__tests__/index.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler-loader-babel-loader/src/index.js, projects/eslint-plugin/configs/general.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/css-parse.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/index.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/plugins/bg.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/plugins/fontawesome.js, projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/plugins/yui3.js
With the gentle nudge by @nhpatt I ended up testing and using the [one-var](https://eslint.org/docs/rules/one-var) rule with the `['error', 'never']` settings. I have tested it inside `liferay-portal` and it produces 72 autofixable errors.
~~I found this [one-var-declaration-per-line](https://eslint.org/docs/rules/one-var-declaration-per-line) ESLint rule. When I plugged it in `liferay-portal` it produced 63 errors, all of which are auto-fixable. The autofix is weird as it just pushes the vars to a new line. The autofix issue can be seen in the 2nd commit.~~
=> feat(eslint-plugin): add one-var rule

projects/js-toolkit/packages/dev-server/src/server.ts
It came from: https://github.com/liferay/liferay-frontend-projects/pull/698
One diff(this specific one) >>> Image >>> Words
=> fix(dev-server): fix a typo for protocol notation

third-party/README.md, third-party/projects/alloy-ui/package.json
Keeping consistency with other packages
=> chore: update alloy-ui package.json to point to proper repository

projects/js-toolkit/packages/dev-server/src/server.ts
fixes https://github.com/liferay/liferay-frontend-projects/issues/729
We walk up directories until we find `modules`, but we never actually account for being at the root itself.
=> fix(dev-server): check if cwd is already at portal root

projects/eslint-plugin/rules/general/lib/rules/no-get-data-attribute.js, projects/eslint-plugin/rules/general/tests/lib/rules/no-get-data-attribute.js, projects/eslint-plugin/rules/portal/lib/rules/no-localhost-reference.js, projects/npm-tools/packages/npm-scripts/src/config/npmscripts.config.js
All of these issues came up while applying in DXP
=> fix: small issues in various lint rules

projects/npm-tools/packages/npm-scripts/src/scripts/check/preflight.js, projects/npm-tools/packages/npm-scripts/src/scripts/check/preflight/checkYarnLock.js
fixes #743
This adds a check to make sure there is no reference to localhost or 127.0.0.1 in our yarn.lock
=> feat(npm-scripts): add preflight check for yarn.lock validity

third-party/projects/alloy-font-awesome/.yarnrc, third-party/projects/alloy-font-awesome/package.json
fixes #746
I was able to verify that `src` is no longer included via `npm pack`. Meaning if we request this package from the npm registry, it should no longer serve the "src" folder.
=> fix(liferay-font-awesome): only pack specific files for npm

projects/js-toolkit/packages/liferay-cli/bin/liferay.js, projects/js-toolkit/packages/liferay-cli/src/dependencies.json, projects/js-toolkit/packages/liferay-cli/src/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/target-liferay/index.ts, projects/js-toolkit/packages/liferay-cli/src/runLiferayCli.ts, projects/js-toolkit/packages/liferay-cli/src/showDocs.ts
This adds the target platforms I published yesterday to the list of available targets when `liferay new <project>` is run.
Right now I'm showing this menu:
I would like to find a more descriptive names, but that's all I could think of.
The main idea we need to convey is that by using a target platform for a specific version you get access to all our APIs through bundler-imports whereas choosing `portal-agnostic` (the `Liferay Portal CE (not using platform's APIs)` you don't. Sadly, expressing that intuitively, and in one line, seems very difficult to me.
=> feat(liferay-cli): add new published target platforms

projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/devDependencies.js
I pulled these version numbers from this release of Liferay portal, https://github.com/liferay/liferay-portal/commit/e64d3f8d5f0b61fe497d4728f1f2c878d8e589c1
=> feat(theme-tasks): update theme dependencies to match Liferay 7.4.13

projects/js-toolkit/scripts/qa/util.js
They were not passing the project type correctly
=> test(js-toolkit): fix QA scripts

.github/workflows/new-portal-release.yml
I think this check should prohibit the workflow from running on forked repos
=> fix: add check for liferay github owner so that this doesn't run on forked repos

projects/npm-tools/packages/npm-scripts/src/typescript/configureTypeScript.js
This adds support to our tsconfig so that they auto-generate and reference the global.d.ts file which we will be adding in https://issues.liferay.com/browse/LPS-131257
=> feat(npm-scripts): add path to global type definition file in liferay-portal

support/packages/github-to-jira-synchronization-tool/mapping-config.json, support/packages/github-to-jira-synchronization-tool/src/config/config.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueAssignedHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueClosedHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueCommentCreatedHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueCommentDeletedHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueCommentEditedHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueCreatedHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueEditedHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueLabeledHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueMilestonedHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueReopenedHandler.js, support/packages/github-to-jira-synchronization-tool/src/event-handlers/issueUnassignedHandler.js, support/packages/github-to-jira-synchronization-tool/src/index.js, support/packages/github-to-jira-synchronization-tool/src/jira/JiraClient.js, support/packages/github-to-jira-synchronization-tool/src/jira/JiraRetryHandler.js, support/packages/github-to-jira-synchronization-tool/src/utils/getOrCreateComment.js, support/packages/github-to-jira-synchronization-tool/src/utils/getOrCreateIssue.js, support/packages/github-to-jira-synchronization-tool/src/utils/isJiraUp.js, support/packages/github-to-jira-synchronization-tool/src/utils/log.js, support/packages/github-to-jira-synchronization-tool/src/utils/runSequentially.js
This is the second PR of the github-to-jira-integration tool:
This PR includes a bunch of enhancements after some testing of the tool, namely:
* Extensive logging to a file. This will allow easier debugging when it is running in the server
* Better events handling. We make sure that the issue or comment exists before doing any operation. This will allow to include issues/comments that are not in jira yet, due to the impasse between exalate expiring and this tool being ready
* Webhooks event are now being handled sequentially. It seems that when creating a github issue with some labels generate two webhooks, one for the issue and one for the label added. If we don't run those sequentially, we may end up with two issues being created. (This didn't happen in my machine but it did happen in …
=> chore(github-to-jira-synchronization): Better error handling and retry mechanism

projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/src/utils/createExportsBridges.js, support/packages/local-npm/lib/index.js
[ [https://issues.liferay.com/browse/IFI-2977](https://issues.liferay.com/browse/IFI-2977) ]
This modifies `npm-scripts` so that if a project declares `exports` in `npmscripts.config.js`, like this:
```javascript
build: {
exports: {
'react': 'react/index',
'react-dom': 'react-dom/index',
}
},
};
```
The `npm-scripts` generate ESM modules that provide a bridge between AMD and ESM worlds, like this:
Where `react.js`, for example, contains:
```javascript
const amdModule = await new Promise((resolve, reject) => {
Liferay.Loader.require(
'liferay!frontend-js-react-web$react@16.12.0/index',
resolve,
reject
);
});
const {
Children,
createRef,
...
version,
__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED
} = amdModule;
export {
Children,
createRef,
...
version, …
```
=> feat: create a tool to be able to generate the AMD to ESM bridges automatically

projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/apps/frontend-js/frontend-js-react-web/package.json, projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/apps/frontend-js/frontend-js-react-web/src/main/resources/META-INF/resources/index.d.ts, projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/apps/frontend-js/frontend-js-react-web/src/main/resources/META-INF/resources/index.js, projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/apps/frontend-js/frontend-js-state-web/package.json, projects/npm-tools/packages/npm-scripts/__fixtures__/typescript/modules/apps/frontend-js/frontend-js-state-web/src/main/resources/META-INF/resources/js/index.ts, projects/npm-tools/packages/npm-scripts/src/typescript/configureTypeScript.js, projects/npm-tools/packages/npm-scripts/test/typescript/configureTypeScript.js
fixes #825
This adds support for TS so that if no main *.ts file exists, we fall back to to an index. d.ts file for the path reference
=> feat(npm-scripts): fall back to checking for index.d.ts if *.ts does not exist

projects/eslint-plugin/README.md, projects/eslint-plugin/configs/general.js, projects/eslint-plugin/rules/aui/docs/rules/no-url.md, projects/eslint-plugin/rules/aui/index.js, projects/eslint-plugin/rules/aui/lib/rules/no-url.js, projects/eslint-plugin/rules/aui/tests/lib/rules/no-url.js
Pretty straightforward, this PR adds a new rule that throws an error when `new A.Url()` is added to the code.
I didn't go with an autofix solution because we don't have any preexisting mentions, and because the returned object has different methods on it compared to the vanilla URL object.
=> feat(eslint-plugin): add new rule against A.Url

projects/js-toolkit/packages/portal-base/src/build.ts
Fixes following problem in @liferay/portal-base v1.0.0.
Steps to reproduce:
```shell
liferay new temp
cd temp
mkdir -p src/test
touch src/test/Test.js
npm run build
```
```
> temp@1.0.0 build /home/ktor/development/projects/lukreo/liferay/modules/application/temp
> liferay build
Building project for target platform: @liferay/portal-7.4
ℹ️ Copying 0 assets...
ℹ️ Running sass on 1 files...
ℹ️ Running babel on 3 files...
Error: ENOENT: no such file or directory, open 'build/test/Test.js'
at Object.openSync (fs.js:497:3)
at Object.writeFileSync (fs.js:1528:35)
at /home/ktor/development/projects/lukreo/liferay/modules/application/temp/node_modules/@liferay/portal-base/lib/build.js:82:26
at Array.forEach (<anonymous>)
at runBabel (/home/ktor/development/projects/lukreo/liferay/modules/applicatio …
```
=> fix: enable building JS files in src child directories, e.g. src/test/Test.js

projects/js-themes-toolkit/packages/liferay-theme-tasks/README.md
I've updated the `liferay-theme-tasks` readme to include:
- how to revert to using libsass for older themes
- a better link to sassOptions, gulp-sass no longer bundles a Sass compiler with it
- add versions of unstyled and styled themes for 7.4
=> docs(liferay-theme-tasks): Update the readme.md

third-party/projects/alloy-font-awesome/package.json
Fixes #818 
For some reason, I do not know why, `liferay-font-awesome (alloy-font-awesome)` started failing when its version got updated to 3.5.0, but I found the culprit. The `main` field was missing inside its `package.json` meaning Node could not find the module.
I've tested this by adding the field to the `liferay-font-awesome/package.json` inside the generated theme and running the Node's `require.resolve('liferay-font-awesome')`.
I couldn't figure out how to `yarn link` these properly so that it uses my local `alloy-font-awesome` instead. Maybe @izaera you can give me a pointer, do I have to run `yarn link` from the `alloy-font-awesome` folder instead of `liferay-theme-tasks`?
=> fix(alloy-font-awesome): Add missing "main" field inside the package.json

projects/amd-loader/src/loader/script-loader.js
=> feat(amd-loader): load scripts as browser modules (i.e.: type='module')

support/packages/github-to-jira-synchronization-tool/mapping-config.json
Add Carlos Correa and remove Victor Galán, Chema and Javi Gamarra
This change doesn't need to redeploy the application. I will update it manually following the instructions here
https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1954447876/Github+to+Jira+synchronization+tool#How-to-modify-the-configuration
but sent this PR is to update the repo so we don't overwrite the configuration next time we redeploy
=> docs(gh-jira-sync): update user mapping

support/packages/local-npm/lib/index.js
Still trying to know what would be the correct sequence to make yarn
reinstall an existing version.
Note that this is forcing yarn to install a newer version with a different
checksum (to make the developer life easier) so it's natural that it
refuses to do it unless forced. That's why I've needed to change this so
many times.
Let's hope this is the last time...
=> fix(local-npm): fix override of @liferay/npm-scripts once more

third-party/projects/alloy-font-awesome/CONTRIBUTING.md, third-party/projects/alloy-font-awesome/README.md
As the title states, this PR updates the three documentation files found under `liferay-font-awesome`.
I've taken some liberties here, removing the (IMO) irrelevant sections of documentation relating to the original font awesome repo.
I have copied over the contributing publishing steps from our other packages, replacing the links with those pointing to liferay-font-awesome testing if it works and it does 💪
=> docs(liferay-font-awesome): Update readme and contributing pages

support/packages/github-to-jira-synchronization-tool/src/Server.js
Fixes #867 
This PR utilizes [Octokit's middleware onUnhandledRequest](https://github.com/octokit/app.js/#createnodemiddlewareapp-options) to add a check for the `/status` page, displaying a simple message if it finds the url.
=> feat(github-to-jira-sync-tool): Add the /status page that displays a message if the tool is running

projects/js-toolkit/packages/portal-base/src/clean.ts
=> refactor(portal-base): don't rely on bundler2 Project for clean task

projects/npm-tools/packages/npm-scripts/contrib/prettier/prettier.js
Fixes #51 
This one was a long journey on my part, getting the Workspace working and then Prettier started causing me issues, etc.
To get this done, I utilized the [debug](https://github.com/kresimir-coko/liferay-frontend-projects/blob/2bcdc8175c4b8c4f8862dfdc8c2253264e2feaab/projects/npm-tools/packages/npm-scripts/contrib/prettier/prettier.js#L20-L35) function in order to get some logging happening which was helpful but took a little bit of figuring out. After I made sure this works in the local Liferay Workspace, I also tested it in this repository and in `liferay-portal` to make sure it properly works since I did split up the conditioning.
=> feat(@liferay/npm-scripts): Give Liferay Workspaces ability to use our Prettier setup with the VSC extension

third-party/projects/alloy-ui/src/aui-datatype/js/aui-datatype-date-parse.js
This is a PR for fixing the following issue: 
https://github.com/liferay/liferay-frontend-projects/issues/879
=> fix(alloy-ui): Wrong date in case the year format is four digit but the value is two digit

guidelines/dxp/liferay_global_event_bus.md, projects/js-toolkit/packages/portal-base/src/build/bundler2.ts
Removing these bits as they didn't actually do anything for us.
We added it here, https://github.com/liferay/liferay-frontend-projects/commit/85b566505d4d0da05490857841b5f5c9082094a6, but I'm not sure we had a use case for adding.
=> fix(portal-base): remove logic that checks for typescript

support/packages/local-npm/bin/local-npm.js, support/packages/local-npm/lib/index.js
This is to be able to use local-npm from bash's PROMPT_COMMAND to show an
emoji indicating which repo is active.
To use this from your .bashrc, simply configure PROMPT_COMMAND to something
like this:
export PROMPT_COMMAND='"$(local-npm registry get --bash-prompt) \u@\h:\w" " \\\$ "'
=> feat(local-npm): add "get registry --bash-prompt" option

.github/workflows/triage.yml
This action should run every monday.
I split the assignee of the issue by day of the month:
0-10: @kresimir-coko
10-20: @izaera
20-31: @bryceosterhaus
=> chore: add github action for triaging issues

projects/npm-tools/packages/npm-scripts/src/utils/convertImportsToExternals.js, projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdExportsBridges.js, projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdIndexBridge.js, projects/npm-tools/packages/npm-scripts/src/utils/getBndWebContextPath.js, projects/npm-tools/packages/npm-scripts/src/utils/runWebpackAsBundler.js, projects/npm-tools/packages/npm-scripts/src/utils/webpackScssLoader.js
We need this to be able to migrate frontend-taglib-clay, for example. It includes source like:
```javascript
import from './perico.scss';
```
Which was previously handled by the bundler. Now we support it with a webpack loader.
=> feat(npm-scripts): support .scss files

projects/npm-tools/packages/npm-scripts/contrib/prettier/prettier.js
Looks like we had created a bug in a previous fix when we did some source formatting.
cc @kresimir-coko can you verify this works as expected for both workspaces and liferay-portal?
=> fix(npm-scripts): update path to node_modules in prettier script

projects/amd-loader/src/loader/loader.js, projects/amd-loader/src/loader/module.js, projects/amd-loader/src/loader/script-loader.js, projects/amd-loader/src/loader/url-builder.js, projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdExportsBridges.js, projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdIndexBridge.js
This adds a new module flag named `useESM` that, when interpreted by the AMD loader, lets JS scripts be loaded with `<script type="module">`.
It is needed to fix [this error](https://github.com/liferay-frontend/liferay-portal/pull/2080#issuecomment-1090195656).
=> feat: bring ESM support to AMD loader

.github/workflows/new-portal-release.yml
As per
https://liferay.slack.com/archives/C3JBR21HA/p1649757130879989?thread_ts=1649671231.502619&cid=C3JBR21HA
since we have adopted the new weekly release lifecycle, we will only
release new artifacts when needed, so there's no point in checking this
automatically for now.
=> chore: disable automatic execution of new portal release workflow

projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdCustomBridges.js
Custom bridges are (hopefully) temporary bridges from ESM to AMD that are
needed by legacy pre-AMD code to work.
So, once we remove the pre-AMD code and the AMD code, I guess we can remove
these...
=> feat(npm-scripts): add customBridges support

projects/npm-tools/packages/npm-scripts/src/jest/mocks/Liferay.js
When running Liferay.ThemeDisplay.getPathContext() inside a DXP instance where we don't change pathContext, it returns an empty string instead of a slash :)
Context: https://github.com/liferay-frontend/liferay-portal/pull/2190#issuecomment-1124230621
Fixes https://github.com/liferay/liferay-frontend-projects/issues/929
=> fix(npm-scripts): Updates getPathContext to DXP's default value

third-party/projects/alloy-ui/src/aui-button-item-deprecated/assets/aui-button-item-deprecated-core.css, third-party/projects/alloy-ui/src/aui-skin-deprecated/css/aui-skin-deprecated.css
LPS-153647 Remove rules that start with *, these rules are fixes for IE7 that we don't support anymore, and it should be removed as we have clients that complain about their accessibility tests failing cause of it
=> LPS-153647 Remove rules that start with *

third-party/projects/alloy-ui/src/aui-tree/js/aui-tree-node.js
Fixes https://github.com/liferay/liferay-frontend-projects/issues/936
https://issues.liferay.com/browse/LPS-153679
Appending nodeContainer to boundingBox results in Wiki Tree to render from top to bottom.
=> AUI-3210 Append container also when we have children inside nodeContainer

third-party/projects/alloy-ui/src/aui-datatable/assets/aui-datatable-core-core.css, third-party/projects/alloy-ui/src/aui-datatable/assets/skins/sam/aui-datatable-core-skin.css, third-party/projects/alloy-ui/src/aui-scroller-deprecated/assets/aui-scroller-deprecated-core.css, third-party/projects/alloy-ui/src/aui-skin-deprecated/css/aui-skin-deprecated.css
I finally cleaned all the IE rules, I guess we should not keep them anymore as we don't support this browsers
I think we should first merge https://github.com/liferay/yui3/pull/26 and then merge this as well and release a new version including the yui3 changes
=> LPS-153647 Remove IE6 IE7 IE8 hack classes no longer needed

projects/npm-tools/packages/npm-scripts/src/config/stylelint.json
I'm adding the `aspect-ratio` property to the list of known properties here, but I'm not sure if maybe upgrading stylelint would fix it too :thinking: 
Also, I haven't tested it, I wanted to first check if this would be the real solution.
=> fix(npm-scripts): add aspect-ratio as known property to stylelint

third-party/projects/alloy-ui/src/aui-image-viewer/js/aui-image-viewer.js
=> fix(alloy-ui): AUI ImageViewer does not attach keydown eventListener on the instance

third-party/projects/alloy-ui/src/aui-datepicker/js/aui-datepicker-delegate.js, third-party/projects/alloy-ui/src/aui-datepicker/js/aui-datepicker-popover.js, third-party/projects/alloy-ui/src/aui-datepicker/js/aui-datepicker.js
fix(alloy-ui): Fix LPS-157062 Calendar event date picker is messy and fail to publish caused by LPS-153254 Render popover inside input parent node for better accessibility
Previous pull https://github.com/liferay/liferay-frontend-projects/pull/960
@bryceosterhaus We need to release a new version, in order to fix LPS-157062 Calendar event date picker is messy and fail to publish. Thanks!
=> fix(alloy-ui): Fix LPS-157062 Calendar event date picker is messy and fail to publish

third-party/projects/alloy-ui/src/aui-autosize/js/aui-autosize-iframe.js
Dear Team,
Our customer finds out an issue related to the autosize iframe, this PR is to fix that issue.
The original request is https://issues.liferay.com/browse/LPP-46052 and the PTR is https://issues.liferay.com/browse/PTR-3286
AUI ticket to fix the issue:
https://issues.liferay.com/browse/AUI-3215
Please help me to verify this and leave comments if any.
Thank you very much,
Chi
=> revert: AUI-1947 Fix odd behavior on Autosize iframe

projects/eslint-plugin/README.md, projects/eslint-plugin/configs/portal.js, projects/eslint-plugin/rules/portal/docs/rules/no-document-cookie.md, projects/eslint-plugin/rules/portal/index.js, projects/eslint-plugin/rules/portal/lib/rules/no-document-cookie.js, projects/eslint-plugin/rules/portal/tests/lib/rules/no-document-cookie.js
- [IFI-3334](https://issues.liferay.com/browse/IFI-3334)
* Add a disabled (for now) ESLint rule to prevent usages of `document.cookie`
* In [LPS-151966](https://issues.liferay.com/browse/LPS-151966), we added a JS API to enforce user consent when managing cookies in DXP. This PR adds a ESLint rule to prevent using the unwrapped `document.cookie`, redirecting devs to that new API. 
* We will send another PR enabling this rule in portal once all DXP use cases have been migrated to the new API.
* Tested this in DXP following these steps:
* Add [this commit](https://github.com/liferay/liferay-frontend-projects/commit/a0d1117ca8197570ef04f5f28b5984279ba51798) enabling this rule in DXP
* Run `yarn link` in `liferay-frontend-projects/projects/eslint-plugin`
* Run `yarn link …
=> feat(eslint-plugin): add ESLint rule to prevent usage of document.cookie

maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/__tests__/alias.test.ts, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/alias.ts
Fixes issue where bundler parses all package.json, even invalid ones.
See internal convo for context: https://liferay.slack.com/archives/C3JBR21HA/p1664782682850919
=> fix(js-toolkit): stop throwing an error and instead return empty json

target-platforms/packages/dxp-7.4/liferay.json, target-platforms/packages/portal-7.4/liferay.json
https://issues.liferay.com/browse/LPS-164784
----
In the future we may want to let the user choose, but for now this should be OK.
The goal of this task is to get rid of needing to use importmaps to make the project work at runtime. This way, we don't need to rely on the importmaps shim and we can ship it turned off by default.
We want to do this because, when using the ES module shims, all ES modules must be routed through the shim to avoid double execution problems like the ones described in https://github.com/liferay-frontend/liferay-portal/pull/2749#issuecomment-1261813605.
=> feat: make liferay-cli use relative imports to obtain React from portal

projects/amd-loader/src/loader/config.js, projects/amd-loader/src/loader/script-loader.js
Since this is done I think it doesn't do any harm to merge it. It may be used in the future if we decide to ship the shims and otherwise it's a simple config setting.
=> feat(amd-loader): add moduleType configuration setting

projects/eslint-plugin/README.md, projects/eslint-plugin/configs/portal.js, projects/eslint-plugin/rules/portal/docs/rules/no-global-storage.md, projects/eslint-plugin/rules/portal/index.js, projects/eslint-plugin/rules/portal/lib/rules/no-global-storage.js, projects/eslint-plugin/rules/portal/tests/lib/rules/no-global-storage.js
- [LPS-158441](https://issues.liferay.com/browse/LPS-158441)
* Add an ESLint rule to prevent usages of `localStorage` and `sessionStorage`
* In [LPS-155901](https://issues.liferay.com/browse/LPS-155901), we added a JS API to enforce user consent when managing web storage in DXP. This PR adds an ESLint rule to prevent using the global `localStorage` and `sessionStorage` objects, redirecting devs to the new wrapped ones.
* Tested this in DXP following these steps:
* Run `yarn link` in `liferay-frontend-projects/projects/eslint-plugin`
* Run `yarn link “@liferay/eslint-plugin”` in `liferay-portal/modules`
* Run `yarn checkFormat`
=> feat(eslint-plugin): add ESLint rule to disable non-wrapped web storage API

projects/npm-tools/packages/npm-scripts/src/config/tsconfig-base.json, projects/npm-tools/packages/npm-scripts/src/typescript/runTSC.js, projects/npm-tools/packages/npm-scripts/test/typescript/configureTypeScript.js
- Removes stale .d.ts files that don't have a source file
- Removes generating types for files in unit tests
=> fix(npm-scripts): update ts generation

projects/npm-tools/packages/npm-scripts/src/scripts/types.js
fixes inconsistencies between `build` and `types` commands
=> fix(npm-scripts): check config if tsc is disables for 'types' command

projects/npm-tools/packages/npm-scripts/src/scripts/build.js, projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdIndexBridge.js
This is needed for https://issues.liferay.com/browse/LPS-165925
=> fix(npm-scripts): don't fail when there's no main entry in build config

projects/npm-tools/packages/npm-scripts/src/utils/runWebpackAsBundler.js
If we export symbols explicitly by configuring this in npmscripts.config.js:
```
build: {
exports: [
{
name: 'metal-component',
symbols: [
'Component',
'ComponentDataManager',
'ComponentRegistry',
'ComponentRenderer',
'addListenersFromObj',
'getComponentFn',
],
},
],
},
};
```
We need to differentiate if the module exports things in ESM or plain CommonJS format. This is important because it makes the treatment of __esModule and default fields different.
=> fix(npm-scripts): fix exports when explicit symbols are used for ESM

maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/__tests__/__fixtures__/project-extended-classifier/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/__tests__/__fixtures__/project-simple-classifier/package.json, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/__tests__/index.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/__tests__/manifest.test.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/index.js, maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/manifest.ts
This is https://github.com/liferay/liferay-frontend-projects/pull/1045 with some refactors on top.
=> fix: Bundle-Version incorrectly generated in JAR manifest if semver classifiers are used

third-party/projects/alloy-ui/src/aui-scheduler/js/aui-scheduler-view-day.js
- [LPS-167272 HR_45 Multiple events are being read in reverse order](https://issues.liferay.com/browse/LPS-167272)
- Related: https://github.com/liferay/yui3/pull/32
This change fixes part of the ticket, an incorrect order of tabs in a day.
In PR, we are changing the order of nodes in DOM. With this change, nodes are accessed through keyboard navigation in chronological order. Order in DOM is irrelevant for display, as the positioning is absolute.
https://user-images.githubusercontent.com/5435511/207394804-926dd0a5-fbf3-46ee-b68f-1b0aebb644d8.mp4
https://user-images.githubusercontent.com/5435511/207394780-75b79717-c1a7-4830-a2c7-78e1940dac8f.mp4
=> fix: LPS-167272 Multiple events are being read in reverse order

projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdIndexBridge.js, projects/npm-tools/packages/npm-scripts/src/utils/getMergedConfig.js, projects/npm-tools/packages/npm-scripts/src/utils/runWebpackAsBundler.js
cc @izaera let me know what you think about this, it seems to work fine locally for me
=> feat(npm-scripts): add support for multiple entry points

projects/js-toolkit/packages/portal-base/src/util/getWebpackConfiguration.ts
=> fix(portal-base): make SCSS files work in Windows

projects/npm-tools/packages/npm-scripts/src/scripts/check/preflight/checkPackageJSONFiles.js, projects/npm-tools/packages/npm-scripts/src/utils/collectDefinedDependencies.js
This adds a preflight check to make sure all dependencies are specified in our global osgi module. 
This also allows for allow-listing certain dependencies in their npmscripts.config.js under "rules"
```
rules: {
'allowed-non-global-dependencies': ['my-module']
}
```
An example failure looks like:
This feature is to compliment https://issues.liferay.com/browse/LPS-168442
=> feat(npm-scripts): add preflight check to validate if dependencies are located in the global npmscripts.config.js

projects/npm-tools/packages/npm-scripts/src/utils/collectDefinedDependencies.js, projects/npm-tools/packages/npm-scripts/src/utils/getMergedConfig.js
This is temporary until we provide a full solution in https://issues.liferay.com/browse/LPS-172749
=> fix(npm-scripts): temporary work around for grabbing rules config at both the root and module level

projects/js-toolkit/packages/js-toolkit-core/src/project/liferayCli/Build.ts, projects/js-toolkit/packages/js-toolkit-core/src/schema/LiferayJson.ts, projects/js-toolkit/packages/js-toolkit-core/src/schema/RemoteAppManifestJson.ts, projects/js-toolkit/packages/liferay-cli/src/new/target-remote-app/templates/liferay.json.ejs, projects/js-toolkit/packages/portal-base/src/build/customElement.ts, projects/js-toolkit/packages/portal-base/src/prepareStart.ts, projects/js-toolkit/packages/portal-base/src/util/createManifest.ts
See https://issues.liferay.com/browse/LPS-172978.
The goal of this PR is to keep using `category.remote-apps` for old projects (that's detected because `liferay.json` is empty for them) but use `category.client-extensions` from now on.
=> feat: use portlet category "Client Extensions" by default, for new projects

projects/npm-tools/packages/npm-scripts/src/config/npmscripts.config.js
Our gradle format tasks handle json
=> fix(npm-scripts): remove json from default fix/check glob

projects/npm-tools/packages/npm-scripts/src/utils/createEsm2AmdExportsBridges.js, projects/npm-tools/packages/npm-scripts/src/utils/runWebpackAsBundler.js, projects/npm-tools/packages/npm-scripts/src/utils/webpackExportCssLoader.js
https://issues.liferay.com/browse/LPS-172747
=> feat: support internal path exports in npm-scripts

projects/npm-tools/packages/npm-scripts/src/jest/mocks/Liferay.js
https://issues.liferay.com/browse/LPS-173985
=> fix(npm-scripts): set getDoAsUserIdEncoded mock as empty string

third-party/projects/alloy-ui/src/aui-image-viewer/js/aui-image-viewer-multiple.js, third-party/projects/alloy-ui/src/aui-image-viewer/js/aui-image-viewer.js
Hi guys,
This is an addition to #1065 .
With previous changes we were not adding an alternative text to thumbnails within image gallery, because 'links' object (Where image information is) is not passed to aui-image-viewer-multiple component.
Let me know if you have any questions.
Thanks.
Regards.
=> fix(alloy-ui): AUI-3217 Adding alternative text for thumbnails in Image Gallery

projects/npm-tools/packages/npm-scripts/src/utils/getMergedConfig.js
Let's see how many versions I need to release until I get this working... :roll_eyes:
=> fix: correctly normalize exports

projects/js-toolkit/packages/js-toolkit-core/src/index.ts, projects/js-toolkit/packages/js-toolkit-core/src/project/liferayCli/Build.ts, projects/js-toolkit/packages/js-toolkit-core/src/project/liferayCli/Dist.ts, projects/js-toolkit/packages/js-toolkit-core/src/project/liferayCli/Project.ts, projects/js-toolkit/packages/js-toolkit-core/src/schema/ClientExtensionConfigJson.ts, projects/js-toolkit/packages/js-toolkit-core/src/schema/ClientExtensionYaml.ts, projects/js-toolkit/packages/js-toolkit-core/src/schema/LiferayJson.ts, projects/js-toolkit/packages/portal-base/src/build/index.ts, projects/js-toolkit/packages/portal-base/src/build/themeSpritemap.ts, projects/js-toolkit/packages/portal-base/src/util/runSass.ts
Config for this CET looks like
```json
{
"build": {
"type": "themeSpritemap",
"options": {
"extendClay": true
}
}
}
```
Icons are placed in the `./src` of your project.
package.json looks like
```json
{
"name": "sample-theme-spritemap-3",
"version": "1.0.0",
"description": "Sample Theme Spritemap 3",
"dependencies": {
"@liferay/dxp-7.4": "*"
},
"scripts": {
"build": "liferay build",
"clean": "liferay clean",
"deploy": "liferay deploy"
}
}
```
=> feat(js-toolkit): adds support for building theme spritemap client extensions

.github/workflows/projects.yml, projects/js-toolkit/packages/liferay-cli/src/dependencies.json, projects/js-toolkit/packages/liferay-cli/src/new/target-theme-spritemap/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/target-theme-spritemap/templates/liferay.json.ejs, projects/js-toolkit/packages/liferay-cli/src/new/target-theme-spritemap/templates/src/foo.svg.ejs
note, I added "(Experimental)" to the name, this way we don't have to make any grand promises :trollface: 
I realized we still use "remote app" for naming stuff. Not sure if I should update that or just use "client extension" now and migrate those later.
=> feat(liferay-cli): add new 'theme spritemap' target type

projects/js-toolkit/packages/liferay-cli/src/new/index.ts, projects/js-toolkit/packages/liferay-cli/src/new/target-theme-spritemap/index.ts
Below is an example if we added `dxpSupport` key to multiple targets. Right now I am only adding experimental to the theme spritemap
=> feat(@liferay/cli): add a way to specify what version of dxp that the target project is supported

.github/workflows/projects.yml, projects/js-toolkit/packages/js-toolkit-core/src/project/liferayCli/Project.ts
This is to add support for multi-CX containers
=> fix(js-toolkit-core): if run from a workspace, traverse up tree to find client-extension.yaml

.github/workflows/projects.yml, projects/npm-tools/packages/npm-scripts/src/scripts/check/preflight/checkPackageJSONFiles.js
Before this change we do a greedy check against ALL package.json files. We had thought that every package.json would need to follow the same dependency rules, but now with the introduction of client extensions, these package.json files will work within their own "workspace" and is isolated from liferay-portal. So now we check if the package.json has a sibling yarn.lock file, and if it does then we don't worry about that project.
=> feat(npm-scripts): ignore dependency check for modules that have their own yarn.lock

projects/npm-tools/packages/npm-scripts/src/utils/getExternalExportsWebpackConfigs.js
So I think webpack uses the path.sep when calling the "test" check. Need to stil actually verify this works in a windows machine.
[This seems to be a known issue as well with webpack](https://github.com/webpack/webpack/issues/2553)
=> fix(npm-scripts): fix path so that it works in windows

projects/npm-tools/packages/npm-scripts/src/utils/getExternalExportsWebpackConfigs.js, projects/npm-tools/packages/npm-scripts/src/utils/webpackExportSvgLoader.js
They work similar to CSS but inline the content directly instead of retrieving it from the server. This is because SVG files don't undergo any process in the server, as CSS files do, so there's no need to make two trips to the server when we can make just one.
=> feat(npm-scripts): support SVG exports

.github/workflows/projects.yml, projects/npm-tools/packages/npm-scripts/src/config/npmscripts.config.js, projects/npm-tools/packages/npm-scripts/src/config/stylelint.json, projects/npm-tools/packages/npm-scripts/src/scripts/format.js, projects/npm-tools/packages/npm-scripts/src/scripts/lint.js, projects/npm-tools/packages/npm-scripts/src/scripts/lint/stylelint/isSCSS.js, projects/npm-tools/packages/npm-scripts/src/scripts/lint/stylelint/lintSCSS.js
Not sure why we didn't have this before
=> fix(npm-scripts): support formatting css files

projects/amd-loader/src/loader/config.js, projects/amd-loader/src/loader/script-loader.js, projects/amd-loader/test/loader/loader.js, projects/amd-loader/test/loader/script-loader.js
We need to propagate the CSP nonce to be able to load AMD scripts.
See:
- https://liferay.atlassian.net/browse/LPS-178066
- https://liferay.atlassian.net/browse/LPS-178066?focusedCommentId=2184413
- https://liferay.atlassian.net/browse/LPS-178066?focusedCommentId=2184418
=> feat(amd-loader): make loader compatible with CSP `script-src '[$NONCE$]'`

maintenance/projects/senna/src/app/App.js
As of today email links such as mailto:john.doe@liferay.com are handled like regular links making a mess figuring out what the protocol, domain, etc. are. 
This PR is trying to fix that.
=> fix(senna): Modify URI generation to properly handle link to emails

projects/js-toolkit/packages/js-api/data-set/index.ts
- [LPS-189354 Standardize renderer APIs](https://issues.liferay.com/browse/LPS-189354)
In the PR, we are introducing the `HTMLBuilder` naming convention to public API:
- `*Renderer` is not quite right, as this is a property of a "Renderer" in DXP.
- `*Component` would not be right, as the function is not [used](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-components-web/src/main/resources/META-INF/resources/ClientExtension.tsx#L21) as a React component. It's used as a plain old function. 
- No suffix, like `FDSFilter`, might be confusing, as there are objects with the same name in DXP.
- We already introduced `htmlBuilder` as an argument of the [ClientExtension component](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fronte …
=> feat(js-api): add FDS CX interfaces with `HTMLBuilder` naming convention

projects/js-themes-toolkit/packages/liferay-theme-tasks/package.json, yarn.lock
https://liferay.atlassian.net/browse/LPP-50503
This fixes the Sass version to 1.64.1 to avoid the log function errors introduced in Sass@1.65.1. I think it would be better if we could review Sass minor and patch versions before passing it on to our users.
@ethib137 @dsanz
=> fix(liferay-theme-tasks): Fix sass version to 1.64.1

projects/js-toolkit/packages/js-api/data-set/index.ts
See https://liferay.atlassian.net/browse/LPS-197299
This is a breaking change but we have not yet released any GA version of @liferay/js-api so there shouldn't be any problem.
Note that I've changed the names of the exported functions and types to meaningful (from the POV of the customer) ones. 
This is because I think we should not tie API names to portal internal stuff. In this case I've left the `HTMLBuilder` concept around because it makes sense, but I've renamed the names of the methods and they don't match the internal ones we use in portal any more.
The rationale for not aligning API and internal names is simple: internal names are subject to change and do change, in fact, as we evolve the product, whereas API names must remain stable forever unless we want to be continuously …
=> feat(js-api)!: improve FDS filter CX interfaces

projects/js-toolkit/packages/js-api/.npmignore
JS files are needed for webpack to work at the liferay portal side.
Additionally, it's possible that we add some runnable stuff to this package in the future, so we readd js files.
=> fix(js-api): readd .js files to npm package

.github/workflows/labeler.yml, projects/js-toolkit/packages/js-api/editor/index.ts
- [LPS-187309 Apply editor config contributor client extensions to CKEditor](https://issues.liferay.com/browse/LPS-187309)
- Related to https://github.com/liferay-frontend/liferay-portal/pull/3902
Adding public types for Editor Config Contributor client extension.
Notes:
- I intentionally named this in a generic way, `EditorConfigTransformer` and not  `EditorConfigContributor`. We plan to add a different CET in the future, that will not use the Java `EditorConfigContributor` framework in DXP. That CET will still be able to use this API, as both will do the same config transformation in the end.
- I don't think we want to manage anything more specific than `[key: string]: any;` for config structure. This is based on the third-party APIs and is likely to change with time. Being so generic …
=> feat(js-api): add types for Editor Config Contributor client extension

projects/npm-tools/packages/npm-scripts/src/utils/findRoot.js
This is needed so that liferay-portal's Playwright tests can use npm-scripts without the `--experimental-standalone` flag.
=> feat(npm-scripts): detect root dir when package-lock.json present

projects/npm-tools/packages/npm-scripts/src/utils/findRoot.js
This is needed so that playwright SF uses its own set of rules.
=> feat(npm-scripts): detect playwright folder as root

maintenance/projects/senna/src/app/App.js, maintenance/projects/senna/test/app/App.js
Hello,
**Issue:**
[ 🐛 Bug report](https://github.com/liferay/liferay-frontend-projects/issues/1188)
Description
[LPS-206518](https://liferay.atlassian.net/browse/LPS-206518)
**Desired behavior:**
Applied Style book's style remain unchanged during navigation
**Current behavior:**
Applied Style book's style changes during navigation as it is overridden by theme's style
**Other information** (environment, versions etc):
Reproducible on Liferay 7.3.x and lower
The same fix has been applied to senna within the DXP code base on 7.4 under [LPS-202135](https://liferay.atlassian.net/browse/LPS-202135)
=> fix: Exchange flipping and style evaluation order to avoid css flicker #1188

projects/npm-tools/packages/npm-scripts/src/utils/getExternalExportsWebpackConfigs.js
When adding an "exports" in a dxp module, we want to at times allow for setting css files. This is the case for `leaflet/dist/leaflet.css` which is used in DXP. However, this fails because it is trying to load an external .png file. By setting url to false, we disable webpack from processing url references.
=> fix(npm-scripts): ignore url options in css as we don't support loading files other than js and css

maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/__tests__/__fixtures__/alias/alias-without-dot.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/__tests__/__fixtures__/alias/main-without-dot.json, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/__tests__/alias.test.ts, maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/alias.ts, maintenance/projects/js-toolkit/packages/liferay-npm-bundler-plugin-replace-browser-modules/src/index.ts
See https://liferay.atlassian.net/browse/LPD-19292
=> fix: handle module aliases that start with "." correctly

third-party/projects/alloy-ui/src/aui-datepicker/js/aui-datepicker-native.js
https://liferay.atlassian.net/browse/AUI-3222
https://liferay.atlassian.net/browse/LPD-22812
This is to fix errors in the console when erasing the hour or minutes of input time. By preventing firing `selectionChange` when the date is invalid, we are able to keep the same behavior without having errors in the log.
If we try to fix this in [input_time/page.jsp](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/input_time/page.jsp#L129) the time will revert to `--:--:-` which will be tedious for users having to reenter the time again.
[Screencast from 04-10-2024 11:12:46 AM.webm](https://github.com/liferay/liferay-frontend-projects/assets/31672551/3082c4b2-f3f9-492f-84de-3031769cbc59)
=> fix(alloy-ui): AUI-3222 Avoid calling selectionChange on invaild dates

projects/npm-tools/packages/npm-scripts/src/typescript/runTSC.js
small patch to avoid some current headaches I am having
=> fix(npm-scripts): don't use prettier plugins when formatting d.ts files

projects/npm-tools/packages/npm-scripts/src/scripts/build.js
I don't need this to be merged fast, but:
1. It makes sense since we already have disable flags for the rest of the toolling.
2. It will be handy when we start using the native sass compiler.
=> feat(npm-scripts): provide a flag to disable sass

projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/css-parse.js
https://liferay.atlassian.net/browse/LPD-3102
When a theme contains the following, the regex stops at the first semicolon, causing issues in the _rtl.css files.
`@import url("https://fonts.googleapis.com/css2?family=Manrope:wght@300;500;600;700;800&display=swap");`
I was able to resolve this by adjusting the regex so it allows multiple semicolons.
Let me know if there are any questions or comments about this.
Thank you!
=> fix(liferay-theme-task): Update regex to allow mulitple semicolons for @import

projects/js-toolkit/packages/js-api/data-set/index.ts
Issue: https://liferay.atlassian.net/browse/LPD-50122
<h1>Allow accessing all row Content in the Cell Renderer Client Extension</h1>
The goal of this PR is to provide support for `itemData` arg in `js-api` , which is needed for Frontend data set cell renderer to access all row items.
=> feat(js-api): add itemData to FDSTableCellHTMLElementBuilderArgs

projects/js-toolkit/packages/js-api/data-set/index.ts
Follow up from: https://github.com/liferay/liferay-frontend-projects/pull/1247
Issue: https://liferay.atlassian.net/browse/LPD-50122
Fixes type of itemData on FDSTableCellHTMLElementBuilderArgs to make it more convenient to use.
=> fix(js-api): Update itemData type on FDSTableCellHTMLElementBuilderArgs

third-party/projects/alloy-ui/src/aui-datepicker/js/aui-datepicker.js
Hello, reviewer!
Currently, the add event calendar modal  is presenting the following behavior: after clicking the Add Event button, the modal opens, but the focus is being set on the first date input field instead of the modal title. 
The purpose of these changes is to make it so that this modal present a consistent behavior with other modal's across the portal, which is: 
- Focusing on the modal title;
- It will read you are inside a modal;
- And that the header is “the header of said modal”;
- Then, with this context, the user begins to navigate the modal. After the first tab, they go to the first interactive element, “close the modal,” and then to the modal-body content.
see related threads: 
[dxp-accessibility](https://liferay.slack.com/archives/C04CPMRMXAL/p1752595166331279) …
=> fix(alloy-ui): Avoid accessibility issues on calendar's add event modal

third-party/projects/alloy-ui/src/aui-datepicker/js/aui-datepicker.js
hey guys, this is a follow up from https://github.com/liferay/liferay-frontend-projects/pull/1255. 
Turns out the nullish coalescing operator (??) is not supported in the JavaScript version used by AlloyUI, this wasn't happening when I ran tests at runtime using the Chrome devtools override feature, but after it got merged, I kept getting this error: `Skip /o/frontend-js-aui-web/aui/aui-datepicker/aui-datepicker-min.js because its content type is not CSS or JavaScript`
So to be safe, I'm using a plain ternary here. thank you!
=> fix(alloy-ui): Use standard javascript for check to avoid compatibility issues
